### ISSUE TITLE
Find multiple match from a template

### ISSUE THREAD

**Issue by Eternahl** [nut-tree/nut.js#115]
**Short overview**
I am looking for a way to find all match on the screen for a template image

**Use case**
Same as the existing `screen.find(...)` method

**Detailed description**
I am thinking about something like  `screen.findAll(...): Promise<Region[]>`
A `maxMatch` parameter might be needed for performance

**Comment by s1hofmann** [comment]
Hi @Eternahl, thanks for reaching out!

`findAll(...)` functionality would be a great feature, I'll check what's possible!
