### ISSUE TITLE
Electron + Windows problems

### ISSUE THREAD

**Issue by bluedarker** [nut-tree/nut.js#126]
**Version**
@nut-tree/nut-js@1.4
Windows 10 version 1809(build 17763.1158)
Electron 8.2.3
Node 12.13.0

**Short overview**
Can't use with Electron, got an error

**Detailed error description**

```
Error: A dynamic link library (DLL) initialization routine failed.
\\?\c:\workspace\electron-quick-start\node_modules\@nut-tree\libnut-win32\build\Release\libnut.node
    at process.func (electron/js2c/asar.js:140:31)
    at process.func [as dlopen] (electron/js2c/asar.js:140:31)
    at Object.Module._extensions..node (internal/modules/cjs/loader.js:1016:18)
    at Object.func (electron/js2c/asar.js:140:31)
    at Object.func [as .node] (electron/js2c/asar.js:140:31)
    at Module.load (internal/modules/cjs/loader.js:816:32)
    at Module._load (internal/modules/cjs/loader.js:728:14)
    at Module._load (electron/js2c/asar.js:717:26)
    at Function.Module._load (electron/js2c/asar.js:717:26)
    at Module.require (internal/modules/cjs/loader.js:853:19)
```

**Steps to reproduce error**

with [Electron quick start example](https://github.com/electron/electron-quick-start)
obtain this error only require @nut-tree/nut-js 

below is my change code in main.js
```javascript
const {app, BrowserWindow,ipcMain} = require('electron')
const path = require('path')
const {
  mouse,
  left,
  right,
  up,
  down
} = require('@nut-tree/nut-js');
function createWindow () {
  // Create the browser window.
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600,
    webPreferences: {
      preload: path.join(__dirname, 'preload.js')
    }
  })
```

this is error screenshot
![image](https://user-images.githubusercontent.com/3773524/79643134-04b14e00-81d4-11ea-98d3-5febd552fb01.png)

**Comment by s1hofmann** [comment]
Hi @bluedarker,

I was able to locate the root cause for this problem and my tests with Electron on Windows were successful.
Could you please give `@nut-tree/nut-js@next` a try?

Best regards 

Simon

**Comment by bluedarker** [comment]
Hi @s1hofmann 
Every thing is normal whit @nut-tree/nut-js@next. 

Thank you for your contribution. It's realy greate moudle

**Comment by s1hofmann** [comment]
Closed with release v1.4.1

**Comment by danielehrhardt** [comment]
I had to install please make sure to have the Microsoft Visual C++ Redistributable installed.

**Comment by s1hofmann** [comment]
In general, please make sure to check [prerequisites](https://github.com/nut-tree/nut.js#prerequisites)
