### ISSUE TITLE
Update npmignore

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#128]
**Short overview**
Update npmignore to limit files included in package

**Use case**
Reduce bloat in published package.

**Detailed description**
Currently the published nut.js package include generated docs, some e2e tests and more.
Since all of this is not required for clients to use nut.js, the npmrc file should be updated to limit published content.

**Comment by sidorares** [comment]
you probably meant [package.json](https://docs.npmjs.com/files/package.json#files) and not npmrc @s1hofmann ?

**Comment by s1hofmann** [comment]
Ah, stupid me!
You're right, @sidorares, I'm not referring to npmrc, but the npmignore file.
