### ISSUE TITLE
Mouse not working on OSX?

### ISSUE THREAD

**Issue by shirshak55** [nut-tree/nut.js#133]
In OSX it is not giving error but also doing nothing however finding image on screen does give correct pixel. Is it some sort of permission issue?
Code

```
  console.log(await mouse.move(right(500)))
  console.log(await mouse.move(right(500)))
```

doesn't move mouse but gives the following result.

```
Mouse {
  native: NativeAdapter {
    clipboard: ClipboardAction {},
    keyboard: KeyboardAction {},
    mouse: MouseAction {}
  },
  config: { autoDelayMs: 100, mouseSpeed: 1000 }
}
Mouse {
  native: NativeAdapter {
    clipboard: ClipboardAction {},
    keyboard: KeyboardAction {},
    mouse: MouseAction {}
  },
  config: { autoDelayMs: 100, mouseSpeed: 1000 }
}
```

**Comment by shirshak55** [comment]
will test on windows and let u know

**Comment by s1hofmann** [comment]
Hi @shirshak55,

you're right, mouse / keyboard access on macOS requires accessibility permissions.
If an application wants to use accessibility features, a permission pop-up should be shown.
If not, you could try to manually add the application you're running the script from.

`Settings -> Security & Privacy -> Privacy -> Accessibility -> Add...`

**Comment by shirshak55** [comment]
Thanks Updated title so it will be helpful to others too.

**Comment by shirshak55** [comment]
@s1hofmann hey there. I don't see cursor moving but sure it moves is there way to make movement visible just so we know where mouse is before doing mouse.leftClick() ?

**Comment by s1hofmann** [comment]
Hi @shirshak55,

how are you connected to your system?
I can't reproduce this behaviour on my machine.
However, I do know that this behaviour occurs when working in a VM.
