### ISSUE TITLE
Add "Running in VM" checkbox to issue templates

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#141]
**Short overview**
Issue templates should include a checkbox to mark whether nut.js is executed in a VM or not.

**Use case**
Reducing questions

**Detailed description**
When running in a VM, visuals may differ from when running on the host system.
For example, a VM may not visually move the cursor despite nut.js changing cursor position inside the VM. (Reproducible with "seamless" VM mode enabled).
By adding a checkbox to indicate whether one is using nut.js inside a VM or not, fewer questions have to be asked to which speeds up investigations.

**Comment by svettwer** [comment]
I'll take care of this :+1:
