### ISSUE TITLE
Mouse & Keyboard tests don't run on Linux CI

### ISSUE THREAD

**Issue by AdrianoFerrari** [nut-tree/nut.js#150]
Thanks for your work on this package!

**Version**
1.4.1

**Short overview**
I upgraded to Electron v9.0.0, spectron v11.0, and latest nut.js (among others).
Something broke along the way, and now Linux tests don't pass if they involve mouse/keyboard interaction on Travis CI. macOS works fine on Travis (yay!), and Windows tests work on Appveyor.

Running tests locally on Linux also works.

**Issue occurs on**
- [X] Travis CI

**Detailed error description**
Errors is `Error: chrome not reachable`:
Full log can be seen on [public Travis project](https://travis-ci.org/github/AdrianoFerrari/gingko-client-trytravis/jobs/691321534):
![Screenshot_2020-05-26_10-03-09](https://user-images.githubusercontent.com/323678/82910803-11466600-9f39-11ea-9315-f61448b441cd.png)

**Steps to reproduce error**
1. Clone `git@github.com:gingko/client.git`
2. Try it on Travis (with [trytravis](https://github.com/sethmlarson/trytravis)).

**Additional content**
Open source repo in question: https://github.com/gingko/client

**Comment by AdrianoFerrari** [comment]
Unrelated to nut.js (xvfb wasn't set to run). Thanks again for your work on this package! Finally, cross-platform automation for Electron :slightly_smiling_face:

**Comment by s1hofmann** [comment]
Hi @AdrianoFerrari,

thanks for the kind words!
I’m happy to see your issue resolved before I could take a look at it! 😃
