### ISSUE TITLE
Evaluate SIFT (or other features)

### ISSUE THREAD

**Issue by svettwer** [nut-tree/nut.js#161]
Due to the [google](https://patents.google.com/patent/US6711293), the SIFT patent expired this year. One should consider to contact the university of britisch columbia to verify that google result and if it is correct, consider adding it to nut.js for image matching improvements.

**Comment by s1hofmann** [comment]
The current release of `opencv4nodejs-prebuilt` does not ship OpenCV's `features2d` / `xfeatures2d` module.

Thus, before being able to use feature matching, a new release has to be built.
