### ISSUE TITLE
screen.find not working after scrolling with mouse

### ISSUE THREAD

**Issue by GLindebyV** [nut-tree/nut.js#171]
**I have a problem with screen.find after using mouse.scrollDown. It cant find a match. If I lower the confidence until it finds a match, it is not the correct one. screen.find works perfectly if not in combination with mouse.scrollDown **

**Not working example**

```js
const { mouse, screen } = require("@nut-tree/nut-js");

async function f1(){

    screen.config.autoHighlight = true;

    await mouse.leftClick().catch(err => { console.log(err) });

    await mouse.scrollDown(1500).catch(err => { console.log(err) });

    await screen.find('test.png').catch(err => { console.log(err)});

}

f1();
```

**Working**

```js
const { mouse, screen } = require("@nut-tree/nut-js");

async function f1(){

    screen.config.autoHighlight = true;

    await screen.find('test.png').catch(err => { console.log(err)});

}

f1();
```

**I am using Windows 10. Am I doing something wrong?**

**Comment by s1hofmann** [comment]
Hi @GLindebyV, thanks for reaching out.

To be honest, so far I've never experienced a situation like this.
I'll try to reproduce said behaviour.

Best regards

Simon

**Comment by s1hofmann** [comment]
So far I never experienced this issue, closing.
Feel free to reopen if there are any updates.
