### ISSUE TITLE
How to activate/focus a window via its name?

### ISSUE THREAD

**Issue by lanzorg** [nut-tree/nut.js#172]
I would like to focus on a window before doing some keyboard shortcuts.  
Is this possible?

**Comment by s1hofmann** [comment]
Hi @lanzorg,

focusing / activating windows is not yet possible. However, there’s already an issue in our native lib which adresses this feature: https://github.com/nut-tree/libnut/issues/18

**Comment by mwarger** [comment]
@s1hofmann @lanzorg  It appears that the issues for libnut have disappeared.  Is there any chance that we could resurrect this issue?  This would be a very helpful feature and would put the windowing functionality at parity with something like robot-js.  Thank you.

**Comment by MystPi** [comment]
I need to do this same thing; has there been any progress on this?

**Comment by s1hofmann** [comment]
> I need to do this same thing; has there been any progress on this?

This will be included in the next release

**Comment by MystPi** [comment]
> > I need to do this same thing; has there been any progress on this?
> 
> This will be included in the next release

Wonderful! Do you have any idea when that might be?

**Comment by s1hofmann** [comment]
> > > I need to do this same thing; has there been any progress on this?
> > 
> > 
> > This will be included in the next release
> 
> Wonderful! Do you have any idea when that might be?

It’ll happen in the next couple of weeks, depending on how much time I manage to spend on it.

**Comment by MystPi** [comment]
> > > > I need to do this same thing; has there been any progress on this?
> > > 
> > > 
> > > This will be included in the next release
> > 
> > 
> > Wonderful! Do you have any idea when that might be?
> 
> It’ll happen in the next couple of weeks, depending on how much time I manage to spend on it.

Awesome, thank you for all the hard work you do; everyone who uses this library appreciates it greatly!

**Comment by s1hofmann** [comment]
@mwarger It’s not yet fully released due to some other topics I followed (https://nutjs.dev/blog/we-have-company) but it will be published with the next release

**Comment by s1hofmann** [comment]
Closed with [release 4.0.0](https://github.com/nut-tree/nut.js/releases/tag/v4.0.0)
