### ISSUE TITLE
How do you call setKeyboardDelay?

### ISSUE THREAD

**Issue by Bestulo** [nut-tree/nut.js#182]
Hi, I've tried a few ways to call `setKeyboardDelay`, but failed every time.

I've tried:

```js
const nut = require('@nut-tree/nut-js')
nut.setKeyboardDelay(1)

const { keyboard } = require('@nut-tree/nut-js')
keyboard.setKeyboardDelay(1)

const { setKeyboardDelay } = require('@nut-tree/nut-js')
```

I just can't find where it is. The docs say it's a property on [KeyboardActionProvider](https://nut-tree.github.io/nut.js/interfaces/keyboardactionprovider.html), but I also don't know how to import this class.

**Comment by Bestulo** [comment]
Also, how do you access the `config` property that the class Keyboard has? I don't find Keyboard to be exported, so I can't import it before creating a new one with the config.

Instead, it [seems to get initialized](https://github.com/nut-tree/nut.js/blob/3734567a136d653e4845be18730345c8e277b925/index.ts), and the config stays in the [class file](https://github.com/nut-tree/nut.js/blob/develop/lib/keyboard.class.ts), not modifiable?

**Comment by s1hofmann** [comment]
Hi @Bestulo,

the intended way to interact with your keyboard is by using the provided `keyboard` instance.
Accessing / modifying config is possible via this instance:

```js
const { keyboard } = require('@nut-tree/nut-js')

(async () => {
    keyboard.config.autoDelayMs = 1000;
    await keyboard.type("This is a test");
})();
```

This pattern also applies to all other instances like `mouse`, `screen`, etc.

You can find additional docs in the provided [sample repo](https://github.com/nut-tree/trailmix) or more specifically the [keyboard sample](https://github.com/nut-tree/trailmix/tree/master/packages/keyboard-test).

**Comment by s1hofmann** [comment]
Closed due to inactivity. Feel free to re-open if you still have questions
