### ISSUE TITLE
OCR API that returns array of all matched instances within confidence threshold

### ISSUE THREAD

**Issue by mstan** [nut-tree/nut.js#185]
**Short overview**
Looking to see the feasibility of an API that returns all instances of a matched image as an array. 
**Use case**
Using it in a game to look at inventory and do reduction management by targeting the hughest number of items first. 

**Detailed feature description**
API returns an array of regions that match criteria. 

I anticipate this can take a while to compute. No time sensitivity in the time to compute.

**Comment by s1hofmann** [comment]
Hi @mstan 👋 

There's already an issue addressing this functionality.
I'll close this issue in favour of #115.
