### ISSUE TITLE
Keyboard methods pressKey and releaseKey ignore updated autoDelayMs

### ISSUE THREAD

**Issue by dancesWithBugs** [nut-tree/nut.js#188]
**Version**

1.5.0

**Description**

One can update the keyboard's auto-delay value by setting `keyboard.config.autoDelayMs` to a new value. The `type()` method will then use the updated value, but `pressKey()` and `releaseKey()` will not. For these, the delay has to be updated via `keyboard.nativeAdapter.keyboard.setKeyboardDelay()`.

This is inconsistent behavior and should be streamlined. I'd suggest updating Keyboard to add a setter that updates the delay in a streamlined fashion for all methods.

**Comment by s1hofmann** [comment]
Closed by #384

**Comment by eun-ice** [comment]
This change causes undesirable behaviour in all our use-cases.

One Use-Case is that we register a global shortcut (say ctrl-alt-shift-s) in our app that sends Ctrl-C to the OS to copy whatever is currently selected on any open App and then reads the value from Clipboard.

To do that have to release all other modifier keys. If we send one releaseKeys with all Modifierkeys except Ctrl we get an error. So we send releaseKey for each modifier Key. The timeout introduced in this commit increases the delay way too much for us.

The other Use-Case is remote controlling the system, having a timeout in releaseKey and pressKey is just slowing down everything.

I don't think it is ever useful to have a delay in releaseKey and even in pressKey I dont see why there ever should be one?

With type the timeout makes total sense.
