### ISSUE TITLE
screen.waitFor() does not return when setting non-default timeout

### ISSUE THREAD

**Issue by dancesWithBugs** [nut-tree/nut.js#189]
**Version**

1.5.0

**Description**

The following minimal example will throw an exception, but the progam will not return. If you set the default value of 5000, it works as expected.

```
const nut = require('@nut-tree/nut-js')
async function run() {
	await nut.screen.waitFor('test.png', 10000) // 5000 would work
}
run()
```

**Issue occurs on**
- [x] Dev/Host system (GNU/Linux)

**Comment by s1hofmann** [comment]
Hi @dancesWithBugs 👋 

Can you confirm this behavior with `@nut-tree/nut-js@next` as well? 
We recently updated the `waitFor` implementation due to a [similar bug](https://github.com/nut-tree/nut.js/issues/174)

**Comment by dancesWithBugs** [comment]
I can confirm that the changes made to @next fix this issue.
