### ISSUE TITLE
Crazy region based screenshot behavior on macOS

### ISSUE THREAD

**Issue by svettwer** [nut-tree/nut.js#194]
**Version**
next

**Short overview**
Screenshots based on Regions on macOS are do not reflect screen content.

**Issue occurs on**
- [x] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**Detailed error description**
I'm using the following workaround from #154 to create a screenshot of a region

```typescript
  const regionCapture = async (
    selectedRegion: NutRegion,
    outputFilename: string
  ) => {
    const regionImage = await (<any>screen).vision.grabScreenRegion(
      selectedRegion
    );
    await (<any>screen).vision.saveImage(regionImage, outputFilename);
  };
```
Based on the provided region, I receive various errors or incorrect images. 
I'm working on a 1920x1080 build agent and configured it as described [here](https://github.com/actions/virtual-environments/issues/393).

**with `new NutRegion(0, 100, 650, 200)` I get:**
![ocr-screenshot](https://user-images.githubusercontent.com/25754312/101634107-83d7e880-3a28-11eb-98af-c4031a9c89bd.png)

**with `new NutRegion(0, 50, 325, 100)` I get:**
![ocr-screenshot](https://user-images.githubusercontent.com/25754312/101635410-3ceaf280-3a2a-11eb-89f3-a6afb8a05695.png)
Just thought a reduction of the resolution could help.

**with `new NutRegion(0, 0, 1900, 1000)` I get:**
```
[Wed Dec 09 2020 13:04:35 GMT+0000 (Coordinated Universal Time)] ERROR: Error in testcase getTextFromRegion: Error: Given width exceeds display dimensions
Error: Error: Given width exceeds display dimensions
    at Object.module.exports.screen.capture (/Users/runner/work/sakuli-ocr/sakuli-ocr/packages/sakuli-ocr/node_modules/@nut-tree/libnut-darwin/index.js:32:16)
    at /Users/runner/work/sakuli-ocr/sakuli-ocr/packages/sakuli-ocr/node_modules/@nut-tree/nut-js/dist/lib/provider/native/libnut-screen-action.class.js:30:46
    at new Promise (<anonymous>)
    at ScreenAction.grabScreenRegion (/Users/runner/work/sakuli-ocr/sakuli-ocr/packages/sakuli-ocr/node_modules/@nut-tree/nut-js/dist/lib/provider/native/libnut-screen-action.class.js:29:16)
    at VisionAdapter.grabScreenRegion (/Users/runner/work/sakuli-ocr/sakuli-ocr/packages/sakuli-ocr/node_modules/@nut-tree/nut-js/dist/lib/adapter/vision.adapter.class.js:43:28)
```

**Whole screen**
Funny enough, when I take a screenshot with `grabScreen`, it looks as expected.
![2020-12-09T13-22-21_error_e2e-suite_getTextFromRegion](https://user-images.githubusercontent.com/25754312/101635764-b1259600-3a2a-11eb-9a59-82244e42761f.png)

**Steps to reproduce error**
As this happens on a build agent and because I've no mac myself, I cannot provide any information, unfortunately.

**Comment by svettwer** [comment]
We were able to reproduce the error during travis to GH Action migration of https://github.com/sakuli/sakuli as well. But this time, the issue also occurred with `grabScreen`. As nut.js is already on GH actions, it would be interesting to get some screenshots from within the build runner. :thinking: 

@s1hofmann Do you have an Idea what could cause this issue? We're currently a little confused about the root cause to be honest. :see_no_evil:

**Comment by s1hofmann** [comment]
@svettwer I'm currently debugging this issue to analyse the root cause.

**Comment by svettwer** [comment]
Awesome! Let me know if I can help. :+1:

**Comment by s1hofmann** [comment]
Will continue later this evening. Might hit you up for a little session, depending on how late my later will be.

**Comment by s1hofmann** [comment]
When capturing the whole screen via `libnut.screen.capture();` and `libnut.screen.capture(0, 0, libnut.screen.width, libnut.screen.height);` gives comparable data.
Once stored, there are offsets present within the data, resulting in an image tilt.

Overall, the issue seems not to be related to the capturing mechanism in `libnut`, will investigate further.

**Comment by s1hofmann** [comment]
@svettwer More details on why this happens can be found here: https://github.com/nut-tree/libnut/issues/44

Looks like a platform problem.

**Comment by s1hofmann** [comment]
And it seems like it’s no longer a problem on Big Sur: https://github.com/nut-tree/libnut/actions/runs/500905237

**Comment by s1hofmann** [comment]
To sum things up: Broken screenshots are caused by and only happen on macOS Catalina. As it is no problem on Big Sur I guess we’ll live with it until explicitly required.
