### ISSUE TITLE
clean way to endlessly find images (+ hide bottom blocks)

### ISSUE THREAD

**Issue by docloulou** [nut-tree/nut.js#198]
**Short summary**
Hello, first, i would say good job for this tool!
i'm looking for a way to endlessly find an image and that without impact performance...

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed question**

I tried a await screen.find(...) in a while(true) loop with a small sleep but i got performance issues after a while...
The workaround is to use waitfor with a long delay ? (any solution to interrupt waitfor ?)

Subsequently, i got several blocks at the bottom of the screen, any idea to hide this ?

![image](https://user-images.githubusercontent.com/14099794/102715868-6cc2b180-42d8-11eb-9be6-676975aa2e54.png)

Thanks you !

**Comment by Nisgrak** [comment]
Any new ideas on this?
