### ISSUE TITLE
Keypress duration

### ISSUE THREAD

**Issue by mk360** [nut-tree/nut.js#199]
Right now we can press a key for a certain duration and the system will properly react to it (it will register as one press). But some applications are more sensitive and will register two or more presses, which is obviously wrong. Is there any way to set how long can the button press be?

**Desired execution environment / tested on**
- Dev/Host system (Windows 10)

**Comment by JonasMatos0** [comment]
Hi, @mk360 
Not sure why this was't answered yet. 
Increasing keyboard.config.autoDelayMs will probably help you to be able to press and release the key without having two key presses accounted.
