### ISSUE TITLE
Enable GitHub Actions

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#200]
**Short overview**
Since Travis effectively dropped support for open source projects we should switch to GitHub Actions

**Use case**
A working CI setup without having monthly costs.

**Detailed feature description**
Travis dropped support for open source projects and would require a monthly subscription (70€ / month).
GitHub Actions have several advantages:
- Linux, Windows and macOS builds in a single system, no more mixture of Travis CI and Appveyor
- Faster builds
- No montly cost (at the moment)
- Large amount of community steps

Without a doubt, moving to GitHub Actions looks like a smart move for us.

**Additional content**
> Please provide any (mandatory) additional data for your desired feature

**Comment by svettwer** [comment]
As a little remark: One could potentially contact travis support and ask them whether they would be so kind to offer monthly open source credits for the project.

https://docs.travis-ci.com/user/billing-faq/#what-if-i-am-building-open-source

But to be honest, I :100:% agree. GitHub Actions is more comfortable and comes with less barriers for open source projects than travis does at the moment.
