### ISSUE TITLE
Strange Behaviour with KVM Switch - OSX 

### ISSUE THREAD

**Issue by hmpmarketing** [nut-tree/nut.js#203]
OS:
MAC OSX BIg Sur
Mac Mini (Latest)

If anybody could help me with this puzzle. I am using the Nut.js to automate some software on my Mac, it works flawlessly!!!.However I am cloning the same exact automation on another exact same configuration (Mac Mini, OSX Big Sur), so using a KVM Switch so that I can see the automation in action on both Minis so switching back and forth is easy and no need for 2 screens.

Here is the snippet of my code in question (more specific, sreen.find() )

```js
while(splashScreen==true){

      try {   
        var isUnexpectedQuit = await screen.find("assets/ok_button.png")
        if(isUnexpectedQuit){
          splashScreen = true
          await moveMouseCoord(1020,570) //Mouse Tools Exec
          await mouse.leftClick()
        }
      }catch(err) {
        console.log(err)
      }

}
```

When I have my KVM switch on Mac Mini 1, the above screen.find works with no issues. The moment I switch my KVM to display the Mac Mini 2 on the screen, trying the above code  will result in waiting for the "ok" button forever, so the code simply stays and does not progress. Meanwhile, on the other Mac Mini2 it works perfectly fine (since the KVM switch has this Desktop on screen)!!

If I swtich back to Mini 1, the code above progresses with no problem at all! However now, Mac Mini 2 also gets stuck waiting for the "ok" button to show up, and in the same way, If I switch the KVM back to Mini 2 the code continues (and again, Mini 1 gets stuck until I "KVM" back to it)....and so on and on!

Im not sure if this is a refresh rate issue, Only thing I can see on Display Properties on my mac is that the Display is "Unknown" on the Mini that does not have KMV active, and the other Mini detects the Display just fine. 

Does the OCR on screen.find depends on refresh rate or anything else? Im puzzled by this, pretty much if I have to make the code above on all machines (total of 3 minis) I would have to have one screen for each as the only way it works is the above.

FYI, the screen resultion is the same on all of them

Thanks again if anyone could give some clues!

Regards

**Comment by s1hofmann** [comment]
Hi @hmpmarketing 👋 

> I am using the Nut.js to automate some software on my Mac, it works flawlessly!!!

That's great to hear!

> Only thing I can see on Display Properties on my mac is that the Display is "Unknown" on the Mini that does not have KMV active, and the other Mini detects the Display just fine.

In order to read screen content, `nut.js` determines the main display to fetch its content.
When there's no display attached (e.g. `Unknown`), `nut.js` can't *'see'* anything.

If you really want to parallelize your scripts I would suggest to:

- either attach a monitor to each Mac Mini
- run your automation script on e.g. a headless Docker container (if it's not specific to macOS)

Best regards

Simon

**Comment by s1hofmann** [comment]
Closed due to inactivity. Feel free to reopen if further questions arise.
