### ISSUE TITLE
ReferenceError: describe is not defined

### ISSUE THREAD

**Issue by mandrasch** [nut-tree/nut.js#219]
Hi,

thanks for providing this project as open source! I just a quick question. I wanted to run the example script from README.md, but got the following error:

```
ReferenceError: describe is not defined
```

Is `describe` from mocha or Jasmine or from something else?

**Desired execution environment / tested on**
Dev/Host system
node: v14.16.1
Installed with `npm i @nut-tree/nut-js --save`, executed with `node app.js`

Thanks in advance! :-)

**Comment by s1hofmann** [comment]
Hi @mandrasch 👋 

The sample shown in [README.md](https://github.com/nut-tree/nut.js/blob/develop/README.md) `describe`s a Jest test.
I updated the snippet since it's not usable out of the box.

Thanks for reaching out!
