### ISSUE TITLE
Backspace latency

### ISSUE THREAD

**Issue by ekrenzin** [nut-tree/nut.js#220]
**Version**
Latest

**Short overview**
The backspace key has significant latency when triggered multiple consecutive times even when keyboard config delay is set low.

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

The backspace key has significant latency when triggered multiple consecutive times even when keyboard config delay is set low. The backspace key appears to ignore the delay setting. After creating a queue of backspace key events, the code will freeze up and will continue pressing backspace for a while.

**Steps to reproduce error**
Press and release the backspace key multiple times rapidly. Can be recreated with for loops.

**Additional content**

Delay has been set to 1ms yet delay is still 300ms:
![image](https://user-images.githubusercontent.com/33398104/114437433-67d18880-9b7b-11eb-9dbd-c789404de4b4.png)

**Comment by ekrenzin** [comment]
Just realized this is all keys that aren't triggered by type()

If this is expected behavior it might be worth documenting?

**Comment by ekrenzin** [comment]
Backspace can be typed faster than it can be triggered.

**Comment by s1hofmann** [comment]
Hi @ekrenzin 👋 

there’s a static delay on single keypresses (a leftover from robotjs, which I initially forked). I see no particular reason for it, so I might consider dropping it.

**Comment by ekrenzin** [comment]
> Hi @ekrenzin 👋
> 
> there’s a static delay on single keypresses (a leftover from robotjs, which I initially forked). I see no particular reason for it, so I might consider dropping it.

Hi s1hofmann, thanks for the quick response, it's much appreciated!

Your explanation makes sense. I'd advocate for dropping it because it removes a lot of control from the developer. Also it was difficult to debug why some keys were more latent than others (after setting the config). Adding documentation regarding the delay would also help.

In the meantime, can you point me in the direction of that delay so I can eliminate it on my own fork? Thanks so much!

**Comment by s1hofmann** [comment]
There are two lines causing the delay in https://github.com/nut-tree/libnut

[_keyTap](https://github.com/nut-tree/libnut/blob/bc9af7200c8e08b6eb9dc6547c81256b48fb1016/src/main.cc#L486)

[_keyToggle](https://github.com/nut-tree/libnut/blob/bc9af7200c8e08b6eb9dc6547c81256b48fb1016/src/main.cc#L555)

Maybe you want to consider opening a PR?

**Comment by ekrenzin** [comment]
Thanks!

I'd be happy to create a PR after/if I get it working and tested. Closing this issue, thanks again!
