### ISSUE TITLE
npm i @nut-tree/nut-js error  [NPM version 7.11.1]

### ISSUE THREAD

**Issue by zhfnjust** [nut-tree/nut.js#223]
**Version**

**Short overview**

**Issue occurs on**
- [ yes/no] Virtual machine 
- [ no] Docker container
- [ no] Dev/Host system

**Detailed error description**

notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
**Steps to reproduce error**

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

hh@ubuntu:~/code/cc$ npm i @nut-tree/nut-js
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/hh/code/cc/node_modules/opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform linux
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/hh/.npm/_logs/2021-04-24T10_11_27_139Z-debug.log
npm ERR! node:child_process:720
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Command failed: npm install @nut-tree/opencv-build-linux@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/hh/.npm/_logs/2021-04-24T10_11_27_139Z-debug.log
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:680:11)
npm ERR!     at execSync (node:child_process:717:15)
npm ERR!     at install (/home/hh/code/cc/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (/home/hh/code/cc/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:26:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1091:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1120:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:971:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:812:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(367) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
npm ERR!       117, 120,  64, 117,
npm ERR!       ... 267 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 3416,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(367) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
npm ERR!     117, 120,  64, 117,
npm ERR!     ... 267 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/hh/.npm/_logs/2021-04-24T10_11_27_513Z-debug.log

**Comment by s1hofmann** [comment]
Hi @zhfnjust 👋 

The latest stable release of `nut.js` (1.6.0) is not yet compatible with `npm` >= 7.
You could try using the current snapshot for the time being until the next stable release.

`npm i @nut-tree/nut-js@next`

**Comment by zhfnjust** [comment]
i change my npm to version 6 first, thank you

**Comment by xCloudzx** [comment]
I'm still getting this error on Node 16.0.0 and NPM 7.10.0. I tried installing from the latest commit too (`npm i github:nut-tree/nut.js#92d6c2408726144fed2e92595ffa14d1809b7d4`).

**Comment by svettwer** [comment]
Hi @xCloudzx 

As @s1hofmann said:
The latest stable release of nut.js (1.6.0) is *not* yet compatible with npm >= 7.

**Comment by s1hofmann** [comment]
Hi @xCloudzx 👋 

Installing from latest `develop` commit works fine, can't confirm:

```bash
┌─[s1hofmann@Simons-MBP] - [/tmp/n] - [2021-04-26 08:45:27]
└─[0] <> npm init -y
Wrote to /private/tmp/n/package.json:

{
  "name": "n",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


┌─[s1hofmann@Simons-MBP] - [/tmp/n] - [2021-04-26 08:45:38]
└─[0] <> npm -v
7.10.0
┌─[s1hofmann@Simons-MBP] - [/tmp/n] - [2021-04-26 08:45:50]
└─[0] <> npm i github:nut-tree/nut.js#92d6c2408726144fed2e92595ffa14d1809b7d4f
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142

added 210 packages, and audited 211 packages in 16s

9 packages are looking for funding
  run `npm fund` for details

found 0 vulnerabilities
┌─[s1hofmann@Simons-MBP] - [/tmp/n] - [2021-04-26 08:46:08]
└─[0] <>
```

**Comment by xCloudzx** [comment]
```
❯ npm init -y
Wrote to /home/user/git/nut-test/package.json:

{
  "name": "nut-test",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC"
}


❯ npm i github:nut-tree/nut.js#92d6c2408726144fed2e92595ffa14d1809b7d4f
npm WARN deprecated har-validator@5.1.5: this library is no longer supported
npm WARN deprecated request@2.88.2: request has been deprecated, see https://github.com/request/request/issues/3142
npm ERR! code 1
npm ERR! path /home/user/git/nut-test/node_modules/opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command sh -c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! Installing prebuilt OpenCV vundefined for plattform linux
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=16.0.0 runtime=node arch=x64 libc= platform=linux)
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/user/.npm/_logs/2021-04-26T19_00_07_689Z-debug.log
npm ERR! node:child_process:747
npm ERR!     throw err;
npm ERR!     ^
npm ERR! 
npm ERR! Error: Command failed: npm install --no-save @nut-tree/opencv-build-linux@undefined
npm ERR! npm ERR! code ETARGET
npm ERR! npm ERR! notarget No matching version found for @nut-tree/opencv-build-linux@undefined.
npm ERR! npm ERR! notarget In most cases you or one of your dependencies are requesting
npm ERR! npm ERR! notarget a package version that doesn't exist.
npm ERR! 
npm ERR! npm ERR! A complete log of this run can be found in:
npm ERR! npm ERR!     /home/user/.npm/_logs/2021-04-26T19_00_07_689Z-debug.log
npm ERR! 
npm ERR!     at checkExecSyncError (node:child_process:707:11)
npm ERR!     at execSync (node:child_process:744:15)
npm ERR!     at install (/home/user/git/nut-test/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:5:5)
npm ERR!     at Object.<anonymous> (/home/user/git/nut-test/node_modules/opencv4nodejs-prebuilt/install/dependencies.js:26:5)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1108:14)
npm ERR!     at Object.Module._extensions..js (node:internal/modules/cjs/loader:1137:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:988:32)
npm ERR!     at Function.Module._load (node:internal/modules/cjs/loader:828:14)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:76:12)
npm ERR!     at node:internal/main/run_main_module:17:47 {
npm ERR!   status: 1,
npm ERR!   signal: null,
npm ERR!   output: [
npm ERR!     null,
npm ERR!     Buffer(0) [Uint8Array] [],
npm ERR!     Buffer(371) [Uint8Array] [
npm ERR!       110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!       101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!       109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!       103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!       105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!       102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!       117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!        99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
npm ERR!       117, 120,  64, 117,
npm ERR!       ... 271 more items
npm ERR!     ]
npm ERR!   ],
npm ERR!   pid: 36105,
npm ERR!   stdout: Buffer(0) [Uint8Array] [],
npm ERR!   stderr: Buffer(371) [Uint8Array] [
npm ERR!     110, 112, 109,  32,  69,  82,  82,  33,  32,  99, 111, 100,
npm ERR!     101,  32,  69,  84,  65,  82,  71,  69,  84,  10, 110, 112,
npm ERR!     109,  32,  69,  82,  82,  33,  32, 110, 111, 116,  97, 114,
npm ERR!     103, 101, 116,  32,  78, 111,  32, 109,  97, 116,  99, 104,
npm ERR!     105, 110, 103,  32, 118, 101, 114, 115, 105, 111, 110,  32,
npm ERR!     102, 111, 117, 110, 100,  32, 102, 111, 114,  32,  64, 110,
npm ERR!     117, 116,  45, 116, 114, 101, 101,  47, 111, 112, 101, 110,
npm ERR!      99, 118,  45,  98, 117, 105, 108, 100,  45, 108, 105, 110,
npm ERR!     117, 120,  64, 117,
npm ERR!     ... 271 more items
npm ERR!   ]
npm ERR! }

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/user/.npm/_logs/2021-04-26T19_00_07_849Z-debug.log
```

## Version Info
Node: 16.0.0
NPM: 7.10.0
OS: Ubuntu 20.04.2 LTS

**Comment by s1hofmann** [comment]
Hi @xCloudzx 👋 

You're running into a different problem.
There are no prebuilds for node 16 as I didn't have to to build them yet, so it fails on install.

```bash
No prebuilt binaries found (target=16.0.0 runtime=node arch=x64 libc= platform=linux)
```

You'll either need to downgrade your node installation or have to wait until I find the time to release prebuilds for node 16.

**Comment by xCloudzx** [comment]
Awesome, downgrading to 15.14.0 worked. I was actually able to install from `@nut-tree/nut.js@next`. Thanks!
