### ISSUE TITLE
Attempt to get active window info shuts down electron devtools and app

### ISSUE THREAD

**Issue by NL33** [nut-tree/nut.js#225]
**Version**
@nut-tree/nut-js: "^1.6.1-next.20210408195718"
electron: 12.0.2
MacOS: 11.1

**Short overview**

I'm hoping to get information about the current active window, including the path to the currently focused file (when available). This might not be possible with getActiveWindow, but I thought I'd give it a try to test it.

However, my attempt to get the currently active window causes the app to shut down, with the dev tools message: 
`DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect.`

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [X] Dev/Host system

**Detailed error description**

I'm trying to use Nut.JS to get information about the currently active window in my electron app. For example, I'd like to get the path to the currently active file.

Here is the code I am using:

```
const { getActiveWindow } = require("@nut-tree/nut-js")

async function getTheWindow(){
    var foregroundWindow = await getActiveWindow()
    await foregroundWindow.title.then(result => {
        console.log('active window = ' + result)
    })   
}
```

When the getTheWindow() function runs, the app screen goes blank, and devtools displays this message:
`DevTools was disconnected from the page. Once page is reloaded, DevTools will automatically reconnect.`

No error is shown (though the problem could be with my syntax--though I'm not sure).

Is there an issue with my syntax causing this, or some other cause?

***
Update: the above error occurred when the action was taken in the renderer process. However, when I put the same code in the main process (ie, main.js), I still get a (different) error: 

```
...exited with signal SIGSEGV
npm ERR! code ELIFECYCLE
npm ERR! errno 1
```
I have tried alternative code:

```
  await getActiveWindow().then(result => {
        console.log('active win = ' + JSON.stringify(result))
   })
```

And this does not cause an error. But it returns the following info (which I assume is not the goal):

`active win = {"nativeActions":{"clipboard":{},"keyboard":{},"mouse":{},"window":{}},"windowHandle":1...9}    `

**Steps to reproduce error**

see above code.

**Comment by s1hofmann** [comment]
I just played around with a little Electron sample.
In my tests I couldn't verify mentioned error, but this is just a quick test.

Could you provide a reproducable sample in a dedicated repo?

Here's the snippet I used:

```js
const {app, ipcMain, BrowserWindow} = require('electron')
const {getWindows, getActiveWindow} = require("@nut-tree/nut-js");
const path = require('path')

let mainWindow;

function createWindow() {
    mainWindow = new BrowserWindow({
        width: 800,
        height: 600,
        webPreferences: {
            nodeIntegration: true,
            contextIsolation: false,
            preload: path.join(__dirname, 'preload.js')
        }
    })
    mainWindow.loadFile(path.join(__dirname, "index.html"))
    mainWindow.maximize();
}

async function getTheWindow(){
    const foregroundWindow = await getActiveWindow()
    const windowTitle = await foregroundWindow.title
    console.log(`active window = ${windowTitle}`);
}

app.whenReady().then(() => {
    createWindow()
    setTimeout(() => getTheWindow(), 5000);

    app.on('activate', function () {
        if (BrowserWindow.getAllWindows().length === 0) createWindow()
    })
})

app.on('window-all-closed', function () {
    console.log("Bye!");
    app.quit();
})
```

**Comment by NL33** [comment]
Thank you, @s1hofmann. Your code works. It's possible that the minor differences in syntax between your code and mine were the difference, but I confess I'm not sure. But happy to have working code.

I can see that using getActiveWindow(), I am able to get the title and the region of the currently active window. Is there other information that I am able to get?

For example, (a) the path to the file and (b) the app being used?

**Comment by s1hofmann** [comment]
Hi @NL33 👋 

At the moment it's only possible to gather either the current active or all available windows to retrieve their size / location and title.
I'm not sure whether it would be possible at all to extract these kind of infos for an open window.

**Comment by NL33** [comment]
Got it. Thanks.
