### ISSUE TITLE
Dockerize application

### ISSUE THREAD

**Issue by lucasfujitareis** [nut-tree/nut.js#229]
**Short summary**

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ x ] Docker container
- [ ] Dev/Host system

**Detailed question**
Hi. Sorry for the noob question but how can I use nut-tree.js inside a docker container.
I managed to write a simple node application as example. But when I create a docker container and try to use it inside the container it doesn't work.
I'm new at this container thing and not so expert with node but I hope someone could help me with that.

Thanks in advance

**Comment by s1hofmann** [comment]
Hi @lucasfujitareis 👋 

Most likely your running into problems since nut.js can’t access a display server inside your container, since most of them are not meant to run GUI applications. You could take a look at existing headless containers which provide an X server.

**Comment by s1hofmann** [comment]
Closed due to inactivity. Feel free to reopen if there are any updates

**Comment by codebanesr** [comment]
I do have X server running
abc          212  0.1  1.9 335444 76104 ?        Ssl  08:38   0:00 /usr/local/bin/Xvnc :1.0 ...

Got the following error:
 Could not open main display
