### ISSUE TITLE
Screen.capture messed up in CI

### ISSUE THREAD

**Issue by gilles-yvetot** [nut-tree/nut.js#230]
**Version**
1.6.0
**Short overview**
`screen.capture` does not give a good screenshot

**Issue occurs on**
- [x] Virtual machine github action running `macos-latest`
- [ ] Docker container
- [ ] Dev/Host system

**Detailed error description**

using `screen.capture`
![activeScreen](https://user-images.githubusercontent.com/4616013/118173695-c3916a80-b3e2-11eb-8550-3c25475877de.png)

using `screencapture` from macos
![screenshotAfterLaunch5](https://user-images.githubusercontent.com/4616013/118173721-cab87880-b3e2-11eb-8768-7a96b9a17efb.png)

**Steps to reproduce error**
```javascript
test(
    `tray icon should be present`,
    async () => {
      await screen.capture(
        `activeScreen.png`,
        FileType.PNG,
        `/tmp/artifacts/tests/runner`,
      )
    },
    25 * 1000,
  )
```

**Comment by s1hofmann** [comment]
Hi @gilles-yvetot 👋 

Could you try running your jobs using `macos-11.0`?

`macos-latest` is still running Catalina, which seems to be the problem. See https://github.com/nut-tree/nut.js/issues/194

**Comment by gilles-yvetot** [comment]
Unfortunately it looks like GitHub does not let me use macOS-11.0 yet

<img width="932" alt="Screen Shot 2021-05-13 at 2 02 03 PM" src="https://user-images.githubusercontent.com/4616013/118187452-ce083000-b3f3-11eb-8e5f-c92e9a97d7f7.png">

**Comment by s1hofmann** [comment]
Closed due to inactivity. Feel free to re-open if there are any updates.
