### ISSUE TITLE
Set position and size of windows?

### ISSUE THREAD

**Issue by NL33** [nut-tree/nut.js#232]
**Short summary**

Is it possible to use NutJS to not only retrieve the size and position of a window, but also set the size and position of a window?

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [X ] Dev/Host system

**Detailed question**

With the window functionality of nut.js, you can get the size and position of open windows on the screen. Is it possible to set the size and position of windows on the screen? 

My guess is this functionality is not available out of the box, but I am inquiring here to see if it would be possible either with some modification or in combination with another library.

One way would be if you could wrap selected windows in an application window. For instance, in an electron app, wrap an electron window over selected windows on the user's screen. Then you could control the size and position through the electron app. Given nut.js's ability to access items from the user's machine, I thought perhaps it could be relevant for this.

Thanks again for the great work.

**Comment by s1hofmann** [comment]
Hi @NL33 👋 

this is definitely doable.
However, `nut.js` lacks the required implementation.
So far there’s no proper definition of what to support, this would be a first thing to do.

Best regards 

Simon

**Comment by NL33** [comment]
Thanks. I'm happy to not have `nut.js` do this, if there are cross-platform alternative ways available. Do you happen to know of any?

In this case, the best for my use case would be to just be able to open a selected window within my electron app window. Note that this is not just displaying a view of the window (which could be possible now), but allowing the user to open an application (like, say, a txt file), and having my electron app wrap around that txt file. So the user could still interact with the file in the same way as always (editing text, etc)., but now it's in an electron window, and I can control the size and position from there.

**Comment by NL33** [comment]
Just a quick follow-up on this. To clarify: what would you require for implementing in `nut.js`? (right now there is the stated goal: for a given window, provide the option to set the size and position of that window.)

If implementing through `nut.js` would take awhile (which would be totally understandable), are there other solutions out there to come close to this functionality in the meantime?

Thanks very much.

**Comment by s1hofmann** [comment]
Closed with [release 4.0.0](https://github.com/nut-tree/nut.js/releases/tag/v4.0.0)
