### ISSUE TITLE
Press Key and Release Key for copy doens't work on Mac OS, Command Key?

### ISSUE THREAD

**Issue by TrofinSorin** [nut-tree/nut.js#237]
**Version**
1.6.0
**Short overview**
I tried to use Ctrl + V on Mac OS and it doesn't work. It works only on Windows. Command Key is not present inside Enum

<img width="438" alt="Screen Shot 2021-06-06 at 12 06 04 AM" src="https://user-images.githubusercontent.com/43543139/120905533-5c6e7b00-c65b-11eb-87d6-fd0e9ef6e661.png">

I have for example a string 'hello' and when i use this it pastes correctly on windows, but on macOS it pastes only the string 'v'.

**What is the Key for Command on Mac? I tried looking in key enum inside library but i can't find it.**

**Issue occurs on**
Mac OS Catalina 10.15.7

**Comment by s1hofmann** [comment]
You can combine multiple keys to add modifiers, see https://nut-tree.github.io/nut.js/classes/keyboard.html#presskey

E.g. for copy / paste you could do something like this:

```js
const { keyboard, Key } = require("@nut-tree/nut-js");

const superKey = process.platform === "darwin" ? Key.LeftSuper : Key.LeftControl;

const copyShortcut = [superKey, Key.C];

const cutShortcut = [superKey, Key.X];

const pasteShortcut = [superKey, Key.V];

(async () => {
    await keyboard.pressKey(...copyShortcut);
    await keyboard.releaseKey(...copyShortcut);
    await keyboard.pressKey(...pasteShortcut);
    await keyboard.releaseKey(...pasteShortcut);
})();
```

**Comment by TrofinSorin** [comment]
@s1hofmann it works perfectly, thank you very much !!!
