### ISSUE TITLE
Keyboard type error Ubuntu 20.10

### ISSUE THREAD

**Issue by sergey-babayan-v** [nut-tree/nut.js#239]
**Version**
1.6.0
**Short overview**

**Issue occurs on**
- [X] Virtual machine
- [X] Docker container
- [ ] Dev/Host system

**Detailed error description**
When try to type email with '@' character it types 2 instead 

**Steps to reproduce error**
Just run Ubuntu 20.10 and run script to type email address.

**Comment by s1hofmann** [comment]
Hi @sergey-babayan-v 👋 

Unfortunately, keyboard typing is still lacking on Linux.
As a workaround, you could try to copy your text to the clipboard via `clipboard.copy(…)` and afterwards paste it via keyboard shortcut, like in https://github.com/nut-tree/nut.js/issues/237

Best regards 

Simon
