### ISSUE TITLE
Keyboard.type with Array of Keys

### ISSUE THREAD

**Issue by chrisspiegl** [nut-tree/nut.js#240]
**Short overview**

At the moment the `keyboard.type(Key.LeftSuper, Key.Right)` expects each key as it's own argument. Idea would be to also support sending an array `[Key.LeftSuper, Key.Right]` so that it can be of dynamic length and combinations.

**Use case**

Dynamically creating shortcut combinations.

I have tried implementing this with `await keyboard.type.apply([Key.LeftSuper, Key.Right])` but that apparently breaks the Promise chain somehow and does not properly await the key clicks.

In my own projects I most often implement these types of features by doing using this:

```js
export const asArray = (x) => Array.isArray(x) ? x : [x]
```

at the beginning of my functions and just always consider that this type of input could be an array.

Open for other solutions and looking forward to using nut.js more.

**Comment by chrisspiegl** [comment]
Closing because I found my own error.

However, I can also see a good reason to reopen to discuss wether it would be worth it to consider supporting arrays as an input here.

### My Solution:

I found out that this actually had nothing todo with the `.apply` not functioning as expected and it had everything todo with how I was using my `setTimeout` for debugging and delaying things.

Turns out just doing `await setTimeout(() => console.log('waited'), 2000)` will not be enough.

Instead I am now using the following function for waiting:

```js
async function wait(ms) {
  return new Promise(resolve => {
    setTimeout(() => {
      console.log(`Waited ${ms} ms`)
      return resolve()
    }, ms);
  });
}
```

And now the wait is working properly and of course with that the

```js
keyboard.type.apply([Key.LeftSuper, Key.A])
```

also is working as expected.

**Comment by s1hofmann** [comment]
Hi @chrisspiegl 👋 

I'm wondering whether your snippet is actually working as expected, since your call to `apply(...)` is missing context?

You should pass the `keyboard` as `this` context:

```js
keyboard.type.apply(keyboard, [Key.LeftSuper, Key.A])
```

Alternatively, you could spread your input array like in https://github.com/nut-tree/nut.js/issues/237

Let me know what you think!

Best regards

Simon

**Comment by chrisspiegl** [comment]
Hi @s1hofmann, after seeing your message on Discord I actually also learned the spread method (just didn't know that that even is a thing that works  🙈 so thank you and I guess that should actually be enough to work with this.

In terms of the missing context: you are correct, in my script I am sending `…apply(keyboard…`  🙈.

I guess this is one of those things where it depends on the knowledge of the developer to know what works and what doesn't 🙈 or what one prefers.

**Comment by s1hofmann** [comment]
Hi @chrisspiegl 👋 

> so thank you and I guess that should actually be enough to work with this

Happy to hear 😃, so I guess I'll close this issue again.

Thanks for reaching out, off to the next issue 😄
