### ISSUE TITLE
Highlighting screen regions window minimized instead closing

### ISSUE THREAD

**Issue by gymadarasz** [nut-tree/nut.js#254]
**Version**
Windows only

**Short overview**
The highlight function leaves a minimized transparent window at the bottom of the screen each time when something highlighted, opaque window is minimized instead of closing properly.

**Issue occurs on**
- [ x] Virtual machine (And real windows machines too, I tried both :) )
- [ ] Docker container
- [ ] Dev/Host system

**Detailed error description**
If I have to be more specific, the bug in the libnut-win32 dependency. If you see the src/win32/highlightwindow.c file, it is using CloseWindow() instead DestroyWindow() however the  CloseWindow() supposed to minimize (but does not destroy) the specified window. We have to close the highlight area properly. For this Windows gives the DestroyWindow() function. 
See more about CloseWindow():
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-closewindow
See more about DestroyWindow():
https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-destroywindow

**Steps to reproduce error**
Just call the screen.highlight(...) method. Each time when this method called you should see a small transparent minimized window at the bottom of the screen.
See on image:
![image](https://user-images.githubusercontent.com/3866135/128975830-baee31a8-db1e-472a-bf0a-47f9a5ae815d.png)

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)
I don't have any more data, I am just using nut.js :)
I was able to fix it with a rebuild of libnut. See my PR here:
https://github.com/nut-tree/libnut/pull/77

**Comment by s1hofmann** [comment]
Hi @gymadarasz 👋 

would you give the snapshot release a try? (`npm i @nut-tree/nut-js@next`)
It includes your fix!

Thanks for your contribution!

Best regards 

Simon

**Comment by gymadarasz** [comment]
Hi, for me it seems to work perfectly :) thank you!
