### ISSUE TITLE
Modifier keys are not properly released.

### ISSUE THREAD

**Issue by ccorcos** [nut-tree/nut.js#264]
**Version**

    "@nut-tree/nut-js": "^1.7.0",

**Short overview**

I'm running this program:

```ts
import * as nut from "@nut-tree/nut-js"

async function main() {
	await nut.sleep(2000)
	await nut.keyboard.pressKey(nut.Key.LeftSuper, nut.Key.LeftShift, nut.Key.P)
	await nut.keyboard.releaseKey(nut.Key.LeftSuper, nut.Key.LeftShift, nut.Key.P)

	await nut.keyboard.type("Open Document")

	await nut.keyboard.pressKey(nut.Key.Enter)
	await nut.keyboard.releaseKey(nut.Key.Enter)
}

main()
```

And in javascript (Chrome), I'm logging the document keydown events:

```ts
document.addEventListener("keydown", event => {
		console.log(
			"keydown",
			event.key,
			event.shiftKey,
			event.metaKey,
			event.altKey,
			event.ctrlKey
		)
});
```

And the result: Shift and Meta keys are still held down when typing. Although they turn off after enter...

<img width="1105" alt="Screen Shot 2021-08-30 at 11 34 03 PM" src="https://user-images.githubusercontent.com/1794527/131454441-12920bcf-6969-4c21-80d7-1bceab2d2363.png">

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system -- MacOS

**Detailed error description**

**Steps to reproduce error**

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by theminor** [comment]
For my system, releaseKey() doesn't seem to be working for any keys. The following code results in the S Key being held down and never released:

```
const { sleep, keyboard, Key } = require("@nut-tree/nut-js");

async function go() {
	await sleep(2000)
	await keyboard.pressKey(Key.S);
	await sleep(2000)
	await keyboard.releaseKey(Key.S);
}

go();
```

Using nut-js version 1.7.0 on Windows 10.

**Comment by s1hofmann** [comment]
Hm, I initially suspected a timing issue, but if also happens with the additional sleep I doubt that. Will have to investigate further

**Comment by s1hofmann** [comment]
Removed it from the 2.0.0 milestone since fixing this issue won’t necessarily require a major release

**Comment by ccorcos** [comment]
Hmm. Still an issue for me...

**Comment by s1hofmann** [comment]
@ccorcos @theminor Would you be available to give the latest snapshot a verify the latest snapshot solves #264 and #273?

`npm i @nut-tree/nut-js@next`
