### ISSUE TITLE
Can't command+click

### ISSUE THREAD

**Issue by ccorcos** [nut-tree/nut.js#273]
**Version**
```
"@nut-tree/nut-js": "^1.7.0",
```

**Short overview**

This is my code
```js
async function main() {
	await nut.sleep(2000)
	await nut.keyboard.pressKey(nut.Key.LeftSuper)
	await nut.mouse.leftClick()
	await nut.keyboard.releaseKey(nut.Key.LeftSuper)
}

main()
```

And I have a codepen with this:

```js
document.addEventListener("click", event => {
		console.log(
			"click",
			event.metaKey
		)
});

document.addEventListener("keydown", event => {
		console.log(
			"keydown",
      event.key,
			event.metaKey
		)
});

document.addEventListener("keyup", event => {
		console.log(
			"keyup",
      event.key,
			event.metaKey
		)
});
```

And I'm seeing:

```
"click" false
"keyup" "Meta" false
```

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

**Steps to reproduce error**

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Removed it from the 2.0.0 milestone since fixing this issue won’t necessarily require a major release

**Comment by ccorcos** [comment]
👋

**Comment by s1hofmann** [comment]
This will be tackled next 👌

**Comment by s1hofmann** [comment]
@ccorcos @morajabi Would you be available to give the latest snapshot a verify the latest snapshot solves #264 and #273?

`npm i @nut-tree/nut-js@next`

**Comment by ccorcos** [comment]
Both work! 🎉 

https://github.com/ccorcos/nut-js-tests

cc @tanishqkancharla

**Comment by s1hofmann** [comment]
@ccorcos Thanks for verifying (and your patience 😂). Will publish a patch release soonish
