### ISSUE TITLE
How to get working with electron 13.0.0 with vue?

### ISSUE THREAD

**Issue by Chappie74** [nut-tree/nut.js#276]
**Short summary**
I currently have a project set up running vue3 and electron 13. 

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**Detailed question**
Whenever I try import the nutjs libraries I run into the issue below. 

![image](https://user-images.githubusercontent.com/21108487/132885518-369359b3-36bf-40a4-8f87-ddf694782f5a.png)

Which after some digging around, it seems I have to add node-loader. So I follow the below as per vue's documentation in adding the node-loader. 

![image](https://user-images.githubusercontent.com/21108487/132885661-75db4216-aa97-477a-a6e9-7abc03566d94.png)

However, after adding this. I've been stuck with another error that I just can't seem to find information on. 

![image](https://user-images.githubusercontent.com/21108487/132885771-661f730d-5685-4bee-ae0c-fa5d7adeff28.png)

Does anyone know what I might be doing wrong here?
Any assistance would be very much appreciated. I have been trying to get this working for  a couple days now.

**Comment by Reiss-Cashmore** [comment]
> **Short summary** I currently have a project set up running vue3 and electron 13.
> 
> **Desired execution environment / tested on**
> 
> * [ ]  Virtual machine
> * [ ]  Docker container
> * [ ]  Dev/Host system
> 
> **Detailed question** Whenever I try import the nutjs libraries I run into the issue below.
> 
> ![image](https://user-images.githubusercontent.com/21108487/132885518-369359b3-36bf-40a4-8f87-ddf694782f5a.png)
> 
> Which after some digging around, it seems I have to add node-loader. So I follow the below as per vue's documentation in adding the node-loader.
> 
> ![image](https://user-images.githubusercontent.com/21108487/132885661-75db4216-aa97-477a-a6e9-7abc03566d94.png)
> 
> However, after adding this. I've been stuck with another error that I just can't seem to find information on.
> 
> ![image](https://user-images.githubusercontent.com/21108487/132885771-661f730d-5685-4bee-ae0c-fa5d7adeff28.png)
> 
> Does anyone know what I might be doing wrong here? Any assistance would be very much appreciated. I have been trying to get this working for a couple days now.

If you could post the project source code that would be helpful. It might be a webpack/loader issue but I'd need to see more about your webpack configs and how you are importing nut.js

**Comment by Chappie74** [comment]
> > **Short summary** I currently have a project set up running vue3 and electron 13.
> > **Desired execution environment / tested on**
> > 
> > * [ ]   Virtual machine
> > * [ ]   Docker container
> > * [ ]   Dev/Host system
> > 
> > **Detailed question** Whenever I try import the nutjs libraries I run into the issue below.
> > ![image](https://user-images.githubusercontent.com/21108487/132885518-369359b3-36bf-40a4-8f87-ddf694782f5a.png)
> > Which after some digging around, it seems I have to add node-loader. So I follow the below as per vue's documentation in adding the node-loader.
> > ![image](https://user-images.githubusercontent.com/21108487/132885661-75db4216-aa97-477a-a6e9-7abc03566d94.png)
> > However, after adding this. I've been stuck with another error that I just can't seem to find information on.
> > ![image](https://user-images.githubusercontent.com/21108487/132885771-661f730d-5685-4bee-ae0c-fa5d7adeff28.png)
> > Does anyone know what I might be doing wrong here? Any assistance would be very much appreciated. I have been trying to get this working for a couple days now.
> 
> If you could post the project source code that would be helpful. It might be a webpack/loader issue but I'd need to see more about your webpack configs and how you are importing nut.js

Hey thanks for the reply. I ultimately decided against using nut.js and took a different approach. I think I had found that it wasn't an issue with nut.js itself either so yeah could very be a webpack configuration issue. Closing issue.
