### ISSUE TITLE
Not able to get window title in WSL2

### ISSUE THREAD

**Issue by QimatLuo** [nut-tree/nut.js#288]
**Short summary**
> X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1
  Serial number of failed request:  8
  Current serial number in output stream:  8

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system
- [x] WSL2

**Detailed question**

I setup WSL2 on Windows 10 with Ubuntu 20.04
I know we need to do some extra setup to be able to access Windows related things from WSL2, so I setup VcXsrv to be able to access the X-Window.
And I'm got success to run the sample code on the README to be able to control mouse from WSL2.

Now I'm try to access the window title and get failed.
But I don't have idea how to solve it.

```js
const { getActiveWindow } = require('@nut-tree/nut-js')

getActiveWindow()
  .then(x => {
    console.log(x)
    return x.title
  })

```
```
Window {
  nativeActions: NativeAdapter {
    clipboard: default_1 {},
    keyboard: KeyboardAction {},
    mouse: MouseAction {},
    window: WindowAction {}
  },
  windowHandle: 1
}
X Error of failed request:  BadWindow (invalid Window parameter)
  Major opcode of failed request:  20 (X_GetProperty)
  Resource id in failed request:  0x1
  Serial number of failed request:  8
  Current serial number in output stream:  8
```

**Comment by s1hofmann** [comment]
To be honest, I have no experience with WSL and therefore no knowledge about how things work in detail.
Would’ve to spend time to learn more about it first

**Comment by QimatLuo** [comment]
Just realize some working feature actually not really works.
For example: `mouse.getPosition()` works in WSL2, but the result Point always the same, no matter where my mouse is.
But if I run the same code on Windows Node.js environment will be works correctly.

Just information for you, may helpful when you debuging WSL related issue.

**Comment by QimatLuo** [comment]
Update for my survey.
Actually those mouse actions works, but not on windows applications.

For example, set few seconds interval and keep doing left click.

Now you run the script in the backend ground, and you will see nothing happens on windows, and no errors.
Then, if you open GUI application with X server, you can see it clicked.

So if the application you try to control is in X server will be fine, but not the application on windows.

**Comment by s1hofmann** [comment]
@reaz1995 summed it up nicely :+1:

Closing
