### ISSUE TITLE
Support Apple Silicon!

### ISSUE THREAD

**Issue by ccorcos** [nut-tree/nut.js#306]
**Short overview**

The new Mac M1 Pro is sweet! But this library doesn't work anymore 😭

**Use case**

**Detailed feature description**

```
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @nut-tree/nut-js@1.7.0: wanted {"os":"linux,darwin,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    linux,darwin,win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chet/.npm/_logs/2021-11-03T15_56_11_865Z-debug.log
```

**Additional content**
> Please provide any (mandatory) additional data for your desired feature

**Comment by s1hofmann** [comment]
Hi @ccorcos 👋 

I'd love to port nut.js to Apple Silicon, however, I do not own an M1 Mac.
Since my current machine is fairly new it's not feasible for me to get a new one, especially since it would only be for this particular reason.

Given this, it still boils down to what I said in #224

> Just a quick update on this issue: As I don't own an M1 Mac I will only spend time on this once nut.js donations allow me to get one or someone is willing to provide me an M1 Mac.

As soon as it's possible, I'm all in 👍

**Comment by ccorcos** [comment]
Ah, I see...

1. This is a decent option for just renting one in the cloud:

https://www.scaleway.com/

<img width="817" alt="image" src="https://user-images.githubusercontent.com/1794527/140175037-8c430b87-640f-4a7d-85bb-2135d643f393.png">

2. I'm happy to help! I'm not terribly experiences with C or any of that though. Any ideas where I should start? 🙏

**Comment by s1hofmann** [comment]
Oh, this actually looks like a pretty solid option, I'll check that out! 👍

Now that I know you're running an M1 Mac, could you give `@nut-tree/nut-js@next` a try?
With image search being optional the actual blocker for Apple Silicon should no longer be included by default.

As I'm currently making quite good progress towards `2.0.0` I'll definitely try out the M1 build, but since I do not know too much about it yet, it's hard to tell where I could need a helping hand. Having a second machine for testing is definitely a good start, so I'll simply reach out to you as soon as I have something to test 👍

**Comment by ccorcos** [comment]
Sounds good! I'll try this out next week -- got a little busy all of a sudden.

What's your game plan for 2.0.0? 😄

**Comment by s1hofmann** [comment]
> What's your game plan for 2.0.0?

The biggest change is the introduction of a little plug-in system which allows one to provide a custom implementation for e.g. image matching. This enabled moving image matching code and it's dependencies into a separate, opt-in package, thus removing the node version dependence in case you don't need any image matching.
And it enables users to publish their own implementations!

Other than that I'm currently re-building the whole image matching package from scratch to reduce the amount of complexity tied to it and to make it independent of node/Electron versions.

Oh, and I'm working on an OCR plug-in!

**Comment by ccorcos** [comment]
Interesting… I’m not using image matching — it seemed kind of brittle where
you can change your ui and break all your tests… Are you using it for
anything?

My current strategy is just to measure the position of the window and the
elements I want to click through a TCP socket to Electron when I want to
click something. And it’s working great!

**Comment by s1hofmann** [comment]
With systems you have control over, like your Electron setup, this is absolutely feasible.

For general UI testing and automation, e.g. when dealing with legacy applications or systems you only have access to via VNC, image based testing is often the only way to go.

**Comment by ccorcos** [comment]
I see. Makes sense.

**Comment by ccorcos** [comment]
```
❯❯❯ npm install --save-dev @nut-tree/nut-js@next
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @nut-tree/nut-js@1.7.1-next.20211115155253: wanted {"os":"linux,darwin,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    linux,darwin,win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chet/.npm/_logs/2021-11-16T07_50_11_190Z-debug.log
```

**Comment by ccorcos** [comment]
Added arm64 to package.json just so it will attempt to install:

```
  "cpu": [
    "x64",
    "ia32",
    "arm64"
  ],
```

Ran `npm run compile` and `npm test`:

```
❯❯❯ npm test

> @nut-tree/nut-js@1.7.0 test
> jest --runInBand

 PASS  lib/screen.class.spec.ts
 FAIL  lib/provider/native/libnut-mouse.class.spec.ts
  ● Test suite failed to run

    dlopen(/Users/chet/Code/js/nut.js/node_modules/@nut-tree/libnut-darwin/build/Release/libnut.node, 0x0001): tried: '/Users/chet/Code/js/nut.js/node_modules/@nut-tree/libnut-darwin/build/Release/libnut.node' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64e')), '/usr/local/lib/libnut.node' (no such file), '/usr/lib/libnut.node' (no such file)
```

Digging into `libnut-darwin` now... (I figure I'll write my notes here)

**Comment by s1hofmann** [comment]
Could you check the output of `lipo -info libnut.node`?

**Comment by ccorcos** [comment]
From the `develop` branch:

```
~/C/j/nut.js ❯❯❯ lipo -info node_modules/@nut-tree/libnut-darwin/build/Release/libnut.node
Non-fat file: node_modules/@nut-tree/libnut-darwin/build/Release/libnut.node is architecture: x86_64
```

I downloaded libnut and built it too. Seems to work:

```
~/C/j/libnut ❯❯❯ lipo -info build/Release/libnut.node
Architectures in the fat file: build/Release/libnut.node are: x86_64 arm64 
```

But I can't figure out how to link the projects together. Somehow the `libnut-darwin` package shows up...

**Comment by s1hofmann** [comment]
So the second snippet is for the `@next` package from npm?

**Comment by ccorcos** [comment]
Simply install @next is problematic:

```
❯❯❯ npm install --save-dev @nut-tree/nut-js@next
npm ERR! code EBADPLATFORM
npm ERR! notsup Unsupported platform for @nut-tree/nut-js@1.7.1-next.20211115155253: wanted {"os":"linux,darwin,win32","arch":"x64,ia32"} (current: {"os":"darwin","arch":"arm64"})
npm ERR! notsup Valid OS:    linux,darwin,win32
npm ERR! notsup Valid Arch:  x64,ia32
npm ERR! notsup Actual OS:   darwin
npm ERR! notsup Actual Arch: arm64

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/chet/.npm/_logs/2021-11-16T07_50_11_190Z-debug.log
```

Need to add `arm64` to the cpus section in the package.json. Then I can give it a try 😄

**Comment by s1hofmann** [comment]
I'll take care of it later today 👍 
Thanks for your debugging help :)

**Comment by s1hofmann** [comment]
@ccorcos Can you give it another try?

**Comment by ccorcos** [comment]
Back in business! Thanks for the help 😄
