### ISSUE TITLE
How would i made a keyboard combination, example : SPACE + CMD + SHIFT

### ISSUE THREAD

**Issue by romain130492** [nut-tree/nut.js#313]
**Short summary**

How would i made a keyboard combination, example : SPACE + CMD + SHIFT,

and with this order ? I was using robot.js and I could do `robot.keyTap('space', ['command', 'shift']);`

Thanks

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**Detailed question**

**Comment by s1hofmann** [comment]
Using `keyboard.type` and the same order as you would enter it yourself on the keyboard: `await keyboard.type(Key.LeftSuper, Key.LeftShift, Key.Space);`
