### ISSUE TITLE
nut.js no work

### ISSUE THREAD

**Issue by richmailYT** [nut-tree/nut.js#315]
**Version**

**Short overview**

**Issue occurs on**
- [x] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
`mouse.leftClick();` refuses to run in electron enviorment on macOS Catalina in NodeJS 16 LTS.

**Steps to reproduce error**
main.js
```
const { app, BrowserWindow } = require('electron')

function createWindow () {
  const mainWindow = new BrowserWindow({
    width: 800,
    height: 600
  })

  mainWindow.loadFile('main.html')

}

app.whenReady().then(createWindow)

app.on('window-all-closed', () => {
  if (process.platform !== 'darwin') {
    app.quit()
  }
})

app.on('activate', () => {
  if (BrowserWindow.getAllWindows().length === 0) {
    createWindow()
  }
})
```
main.html
```
https://pastebin.com/Qrajrwnk
```
autoclicker.js
```
https://pastebin.com/78bGcUUx
```

**Additional content**
MacOS Catalina 10.15.7, NodeJS 16 LTS, lastest electron and lastest nut.js

**Comment by s1hofmann** [comment]
Hi @richmailYT 👋 

Did you check accessibility permissions, as mentioned

**Comment by richmailYT** [comment]
> Hi @richmailYT 👋
> 
> Did you check accessibility permissions, as mentioned [in the readme?](https://github.com/nut-tree/nut.js#macos)

Yes. I havve given VSC and the terminal permition to control my mouse

**Comment by s1hofmann** [comment]
Could you please add another sample to reproduce?

**Comment by richmailYT** [comment]
@s1hofmann https://github.com/richmailYT/AutoClicker 
node 16.13.0 and electron 12.2.3

**Comment by s1hofmann** [comment]
Could you please add your terminal output starting from when you execute `npm start`?
I'm expecting to see an error, as your code is not correct.

```js
const { app, BrowserWindow, ipcMain} = require('electron');
const path = require('path');
const mouse = require('@nut-tree/nut-js');

const createWindow = () => {
...
```

You're importing the whole module as `mouse`, so in order to get anything moving you'd have to change this

```js
async function mouseClick() {
  await mouse.leftClick();
  console.log("ran"); //this wont run
}
```

into this

```js
async function mouseClick() {
  await mouse.mouse.leftClick();
  console.log("ran"); //this wont run
}
```

The preferred way, however, would be to use destructuring like

```js
const { mouse } = require("@nut-tree/nut-js");

async function mouseClick() {
  await mouse.leftClick();
  console.log("ran"); //this wont run
}
```

**Comment by richmailYT** [comment]
@s1hofmann Thank you! that fixed it. you should make the documentation in trailmix clearer

**Comment by s1hofmann** [comment]
It’s a public repo, feel free to create a PR for improvements
