### ISSUE TITLE
template-matcher is not compatible with arm64 (Apple Silicon M1)

### ISSUE THREAD

**Issue by BrTkCa** [nut-tree/nut.js#331]
**Short summary**

template-matcher tool is not compatible with arm64 (Apple Silicon M1)

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [X] Dev/Host system

**Detailed question**

I use the new MacBook Air M1 and testing the feature `screen.find` got the issue:

`Reason: 'Error: No ImageFinder registered'`

Looking at the https://nutjs.dev/blog/going-on-devlog/ I tried to test it (I'm aware that it's in development) but it failed because is not compiled to arm64. There are some way to re-compile locally to arm64?

Also, template-matcher is only available in rpm registry...maybe it'd be good to have it in github =]

**Comment by BrTkCa** [comment]
> I don't think it's supported at this time. For now, I think it is better to run the terminal as rosetta to avoid this problem.

This is a good option, thank you @TetsuakiBaba . I'll left the question opened for future improvement.

**Comment by s1hofmann** [comment]
@BrTkCa I have some news regarding Apple Silicon support: https://nutjs.dev/blog/new-years-news
