### ISSUE TITLE
Error during load: NODE_MODULE_VERSION not match

### ISSUE THREAD

**Issue by nonoroazoro** [nut-tree/nut.js#335]
Env:
- MacOS Catalina
- @nut-tree/nut-js@1.7.0
- electron@15.3.3
- electron-builder@22.14.5

Issue:
Met the error `App threw an error during load`.

<img width="1451" alt="图片" src="https://user-images.githubusercontent.com/383132/145535586-bd914dc6-9f82-4340-9bdf-9c91ac583fa1.png">

I've tried to install and rebuild `opencv4nodejs-prebuilt`, but still doesn't work.

Does anyone have an idea how to make it work?

**Comment by s1hofmann** [comment]
Electron 15 is not supported by `opencv4nodejs`.

Which steps did you take to rebuild it?

**Comment by nonoroazoro** [comment]
> Electron 15 is not supported by `opencv4nodejs`.
> 
> Which steps did you take to rebuild it?

Tried `electron-builder install-app-deps` and `electron-rebuild -f -w opencv4nodejs-prebuilt -v 15.3.3`, but not work.

**Comment by s1hofmann** [comment]
Latest supported version with prebuilds is Electron v13.x.x, later versions have to be built manually.

You can enable building from source via 

`npm_config_build_from_source=true npm_package_config_opencv=4.1.1-7 npm i @nut-tree/nut-js`

**Comment by nonoroazoro** [comment]
Thank you very much! I'll try it.
