### ISSUE TITLE
Clipboard paste not working in 2.0.0 RC1

### ISSUE THREAD

**Issue by GaurangTandon** [nut-tree/nut.js#347]
**Version**

- `"@nut-tree/nut-js": "^2.0.0-RC1",` (from `package.json`)

I am using Node v14.15.1 and electron v12.2.3 if that matters.

**Short overview**

**Issue occurs on**
- Dev/Host system: Windows 10 (Version 20H2 OS Build 19042.1415)

**Detailed error description**

Clipboard copy/paste does not work.

**Steps to reproduce error**

```javascript
const { clipboard, keyboard, Key } = require("@nut-tree/nut-js");
await keyboard.pressKey(Key.A);
await keyboard.pressKey(Key.B);
await keyboard.pressKey(Key.Space);
const str = "Hello World";
await clipboard.copy(str);
await clipboard.paste();
```

Keys `ab<space>` get pressed, but paste does not work. I have tried this on both Notepad and MS Word.  

Copy works because I checked my clipboard contents does get updated to `"Hello World"`. But paste does not work.

There is no error seen anywhere, just nothing happens in the code.

**Additional content**

Thanks for making this tool! I believe I'm surely making some silly mistake otherwise this functionality would work as advertised. I would be happy to contribute a clipboard example to https://github.com/nut-tree/trailmix if that'd help you, as I can't seem to already find any.

**Comment by GaurangTandon** [comment]
Apologies, I now realized that `paste` _returns_ the `string` instead of pasting it into the editor. So, I used this and it worked:

```javascript
await clipboard.copy("Hello");
await keyboard.pressKey(Key.LeftControl, Key.V);
```

However, I wonder if this is susceptible to any OS-/application-level inconsistencies. For example, on Mac, it would be `Cmd-V`. Then, on certain applications, Ctrl-V may be overridden. Or the user may have rebound the Ctrl-V key to some other action on their operating system.

Therefore, I ask: do you plan to expose an API to systematically invoke a low-level/OS-level "paste" (into the currently focused editor) command? Furthermore, this low level command could have flavors such as "pastePlainText" or "pasteHTML".

**Comment by s1hofmann** [comment]
Hi @GaurangTandon 👋 

I see you fell into my poor API naming trap as well.
Indeed, `clipboard.paste` returns the current clipboard content, instead of actually pasting it to the system. I might consider renaming it for the future.

I'm currently not planning to provide such abstractions, I'm still mostly focussing on making all low-level things stable.

You could build your own, cross-platform suitable solution to this, see e.g. https://github.com/nut-tree/nut.js/issues/237

**Comment by GaurangTandon** [comment]
Thanks @s1hofmann for the prompt response and the valuable link. 

Since you have more experience in this field, may I ask you: do any other frameworks provide a more direct "paste" invocation? For example, in the web we have `document.execCommand("paste")`.

**Comment by s1hofmann** [comment]
Hi @GaurangTandon 👋 

I did not add such a shortcut because it’s not 100% consistent across all platforms. I decided thats it’s better to provide primitives to implement it in a flexible way. 
TBH, I don’t know how other frameworks deal with this
