### ISSUE TITLE
`screen.find` function is not working on 2.0.0 RC1

### ISSUE THREAD

**Issue by Ricardonacif** [nut-tree/nut.js#348]
**Version**
![image](https://user-images.githubusercontent.com/865780/147437455-de28a330-38ee-4d39-bb19-aeb002b2ae94.png)

**Short overview**
When I try to run a `screen.findAll` or `screen.find`  functions, I always get:
```
Searching for undefined failed. Reason: 'OpenCV Error: (!_src.empty()) in cv::cvtColor, in file C:\projects\npm-opencv-build\opencv\opencv\modules\imgproc\src\color.cpp, line 182, status -215'
```
Apparently it's not finding the image, but the same code works on older versions (expect the `findAll` function which is new).

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [X] Dev/Host system

**Comment by s1hofmann** [comment]
Hi @Ricardonacif 👋 

There’s a breaking change regarding the usage of `screen.find` with the next major release.
See https://nutjs.dev/docs/migrations/2_0_0#screenfind for how to deal with it.

The error message is unclear in this case, it’ll be addressed in the next RC.
