### ISSUE TITLE
Update libnut to 2.1.4 to fix Windows scaling issue

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#349]
**Short overview**
libnut 2.1.3 had a bug with regards to Windows display scaling which is fixed in 2.1.4

**Comment by nellydocs** [comment]
Windows scaling still not working properly for me.
I wish i could add more details but i dont know what to report.
Please let me know what information i should append.

![image](https://user-images.githubusercontent.com/71311423/151713599-1addb99c-bfb3-4987-8b29-76fb387952a6.png)
![image](https://user-images.githubusercontent.com/71311423/151713644-1c17a3e4-c02c-467f-af3d-b9cf139d7437.png)
