### ISSUE TITLE
Module not found when packaged using Electron Forge

### ISSUE THREAD

**Issue by ImPhantom** [nut-tree/nut.js#356]
I'm currently trying to migrate one of my projects from RobotJS to an actively maintained alternative, and found this. But I'm having trouble including this module in the packaged version of my Electron application. Everything works fine when just running the app via 'electron-forge start', but the binaries/installers produced by the package/make scripts don't seem to include NutJS at all. 
Resulting in `Cannot find module '@nut-tree/libnut-win32'`

I'm using the [Webpack Template](https://www.electronforge.io/config/plugins/webpack) for Electron Forge. Which seems to handle native modules quite well. But I'm not sure whats happening here...

I'm fairly sure this isn't an issue with the actual library itself, but more a webpack/electron configuration issue that I'm just hoping someone might have some insight on. Apologies if this isn't the best place to ask this question, but I figured its better than not asking at all and pulling my hair out...

[Project Source](https://github.com/ImPhantom/Clickr/tree/rewrite)

**Comment by s1hofmann** [comment]
Hi @ImPhantom 👋 

I had a quick look on this issue and noticed that the `@vercel/webpack-asset-relocator-loader` plugin seems to be tripping over the dynamic require 

```js
require(`@nut-tree/libnut-${process.platform}`);
```

used in `@nut-tree/libnut`.
I pushed an update, could you please check the latest snapshot of nut.js?

```shell
npm i @nut-tree/nut-js@next
```

Thanks for reaching out!

Best regards

Simon

**Comment by ImPhantom** [comment]
That seems to have solved the problem completely. Thank you for the help, and for such a quick response!

**Comment by jonkad** [comment]
Hi ✌️  ,

I'm also currently  switching from robotJS to nut.js and it seems I've got an equal issue, but with electron-builder...
Maybe this has also happened to someone whoe have a solution?

Thanks a lot 😄 

![image](https://user-images.githubusercontent.com/12885987/151341509-ed077aee-1bc8-4a55-92ac-99e6a901ada9.png)

```
"dependencies": {
        "@nut-tree/nut-js": "^2.0.2-next.20220121214305",
        "electron-updater": "^4.6.1",
    },
    "devDependencies": {
        "electron": "^15.3.5",
        "electron-builder": "^22.14.5",
        "electron-notarize": "^1.1.1",
        "electron-rebuild": "^3.2.7",
        "electron-updater": "^4.6.1"
    }
```

**Comment by GaurangTandon** [comment]
I just logged an issue in the electron-forge repo when using their webpack template on Windows. I think the issue is related to `@vercel/webpack-asset-relocator-loader`, hence I am linking it here:  https://github.com/electron-userland/electron-forge/issues/2901

I believe since you've already patched this, it should not be an issue from this side. But if you think it is from this side, I'll be happy to make a PR/help find the issue.

**Comment by s1hofmann** [comment]
@GaurangTandon Thanks for the heads up! 👍
