### ISSUE TITLE
Nut.js unable to send key holds properly inside games

### ISSUE THREAD

**Issue by Bare7a** [nut-tree/nut.js#359]
**Version:**  2.0.0

**Issue occurs on:**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system - Windows 11

**Description:**

When trying to use Nut.js in games, for some reason the inputs doesn't get triggered by the them.

One weird example is with Minecraft, where when I try to hold "W" for 5 seconds the character doesn't move, but if I enable the ingame chat, the "W" key appears. I've tried to press "W" multiple times before triggering the releaseKey function in Nut.js, but the result is the same - the character doesn't move, and if the chat is enabled I can see that the "W" key is actually spammed.

![Single keyPress, single keyRelease](https://user-images.githubusercontent.com/10557728/149149257-84f66120-e3ca-47f4-aaa4-dbc1d79afa13.png)
![Multiple keyPress, single keyRelease](https://user-images.githubusercontent.com/10557728/149149165-c38012dd-b13a-4706-b9eb-bf55611fc42f.png)

**Comment by cheul123a** [comment]
try run as admin i solved same problem with this.

**Comment by Bare7a** [comment]
> try run as admin i solved same problem with this.

I've tried doing that and it still has the exact same problem, the interesting thing is that when I try using RobotJS it works.

**Comment by SteveDeWald** [comment]
I had this problem too.  I think anticheat software might be interfering with it.  RobotJS works though.
