### ISSUE TITLE
Driver level keyboard input support

### ISSUE THREAD

**Issue by bymomo** [nut-tree/nut.js#364]
**Short overview**
Driver level keyboard input support
**Use case**
await keyboard.pressKey(Key.Left);
**Detailed description**
Keyboard input is not supported in many games. It may be blocked by the anti cheating system. It may require driver level keyboard input to be effective, such as WINIO
**Additional content**
> Please provide any (mandatory) additional data for your enhancement
Nut JS is very easy to use. Want to add this feature or provide other suggestions. Thank you for your creation

**Comment by s1hofmann** [comment]
Hi @bymomo 👋 

this issue is already in progress, I’ll regularly update here

**Comment by bymomo** [comment]
> 嗨@bymomo 👋
> 
> @bymomo
> 
> 这个问题已经在进行中，我会定期在这里更新
> 
> 这个问题已经在进行中，我会在这里定期更新

After testing, I run the script as an administrator to support my game control, but I'm not sure all games support it
