### ISSUE TITLE
Module could not be found | libnut.node

### ISSUE THREAD

**Issue by jonkad** [nut-tree/nut.js#365]
Hi ✌️  ,

I'm also currently  switching from robotJS to nut.js and it seems I've got an [equal issue](https://github.com/nut-tree/nut.js/issues/356), but with electron-builder...
Maybe this has also happened to someone who have a solution?

Thanks a lot 😄 

![image](https://user-images.githubusercontent.com/12885987/151341509-ed077aee-1bc8-4a55-92ac-99e6a901ada9.png)

On unpacked asar the message mentioned C:\Program Files\ Control\resources\app\node_modules\@nut-tree\libnut-win32\build\Release\libnut.node

```
"dependencies": {
        "@nut-tree/nut-js": "^2.0.2-next.20220121214305",
        "electron-updater": "^4.6.1",
    },
    "devDependencies": {
        "electron": "^15.3.5",
        "electron-builder": "^22.14.5",
        "electron-notarize": "^1.1.1",
        "electron-rebuild": "^3.2.7",
        "electron-updater": "^4.6.1"
    }
```

**Comment by jonkad** [comment]
Hi @s1hofmann,

this happend after shipping. On dev mashine and some others everything is fine.

**Comment by jonkad** [comment]
Ah, is that necessary on the target machines as well? 
On the DEV / Build machine it is of course installed.

**Comment by jonkad** [comment]
Thank you for your assistance! And forgive me for the carelessness 😉

**Comment by augustnmonteiro** [comment]
@s1hofmann is there a way to ship the runtime requirements together with the installer?

**Comment by GaurangTandon** [comment]
Hi @s1hofmann 👋 

Often, the users of automation apps (think support desk agents) are not admin users. So, if an app built using libraries like nut.js is shipped to them, they will not have the permission to install VCRedist (Windows requirement) on their system. 

This is also noted by the MS official docs ([link](https://docs.microsoft.com/en-us/cpp/windows/choosing-a-deployment-method?view=msvc-170)) and their suggestion in such case is to do "local deployment": copy the relevant `.dll` files in the same folder as the `.node`/`.exe` files.

I tried the same technique with libnut.node, unfortunately, it did not work. I want to confirm from you if you are aware of any specifics in libnut.node that may cause local deployment to not work?

Local deployment is crucial for such types of applications (non-admin users), and also for building portable binaries of apps. So, it would be great if it worked.

**Comment by s1hofmann** [comment]
https://github.com/nut-tree/libnut/pull/130

**Comment by GaurangTandon** [comment]
Thanks @s1hofmann , I just tried this again and it works! (imported libnut snapshot and did `libnut.keyTap/typeString`, on a PC without VCredist installed)

**Comment by GaurangTandon** [comment]
You may wish to update the docs for [first steps on Windows](https://nutjs.dev/tutorials/first_steps) once a new nut.js release is out.
