### ISSUE TITLE
Double click

### ISSUE THREAD

**Issue by ricardopolo** [nut-tree/nut.js#373]
I'm trying to simulate a double click in mac. In RobotJs I use the double click option http://robotjs.io/docs/syntax#mouseclickbutton-double

what can I use for doing a double click in Nutjs?

I tested sending two click events on after each other and I does not work

Thanks

**Comment by ricardopolo** [comment]
@s1hofmann any advice?

**Comment by s1hofmann** [comment]
Unfortunately nut.js does currently not expose a dedicated double-click method which would be required for macOS.
One way to work around this could be the `Cmd+O` shortcut, in case you’re trying to open an item

**Comment by ricardopolo** [comment]
Do you think I will be implement soon?

I was thinking of nut as a replacement for robots, but the lack of double click of drag won’t allow us

thanks a lot

**Comment by s1hofmann** [comment]
Hi @ricardopolo 👋 

To be honest, this has a rather low priority at the moment.
You're actually the first one to report this issue (same for #374) and I've yet to decide how this should be best reflected API wise.

**Comment by ricardopolo** [comment]
Thanks @s1hofmann. 

I hope in the mid term this library could be a full replacement of RobotJs. You are doing a great library!!

**Comment by s1hofmann** [comment]
I'll give you a ping in here once it's available

**Comment by s1hofmann** [comment]
/cc @ricardopolo 

You can give `mouse.click(Button.LEFT/Button.MIDDLE/Button.RIGHT)` and `mouse.doubleClick(Button.LEFT/Button.MIDDLE/Button.RIGHT)` a try with the latest snapshot release.

```
npm i @nut-tree/nut-js@next
```

**Comment by s1hofmann** [comment]
Hi @adamjerickson 👋 

I just did a double check and confirmed that double clicking is working as expected on my macOS machine.
Tested on both node 18 and Electron 24.1.3

**Comment by adamjerickson** [comment]
The app I'm building this into is on node 16.4 with same version of electron. Do you have an easy way to test with that version of node? Otherwise I'll try to bootstrap something.

**Comment by s1hofmann** [comment]
I did another test with Electron 16.2.8 which worked flawlessly.

See https://share.cleanshot.com/YFZJLJpZ

**Comment by adamjerickson** [comment]
Okay, thanks. Must be something in my code. I'll dig deeper. Thanks.

**Comment by adamjerickson** [comment]
Is there a reason you have the doubleClick call inside the Click promise resolution? Does it need to be after a single click?

**Comment by s1hofmann** [comment]
The simple reason for this is to shift the focus away from the Electron window.

Without it the double click on the icon wouldn’t work, because one of the clicks would first shift the focus.
Maybe something to consider for you as well?

**Comment by parikshit-dp** [comment]
@s1hofmann maybe you can this in the documentation. I too had similar problem and first doing a click and then doubleClick worked. Thanks!
