### ISSUE TITLE
Instant drag mouse

### ISSUE THREAD

**Issue by ricardopolo** [nut-tree/nut.js#374]
Any way to instant drag the mouse?
Like `setPosition` but whit button held?

In robotjs: http://robotjs.io/docs/syntax#dragmousex-y

**Comment by s1hofmann** [comment]
Hi @ricardopolo 👋 

I just had a look at your mentioned example and tested it on macOS, where it actually does not work.
Could you please give an example of your usage + the OS you're on?

Otherwise I'll close this issue soonish.

**Comment by ricardopolo** [comment]
It works in my case in windows. Basically I created a Remote Desktop like solution and move the remote computer using RobotJs. Would love to do it with Nut.js. 

The instant drag  is useful, as example, when dragging a file in windows explorer

**Comment by s1hofmann** [comment]
I’ll have a look on Windows specifically

**Comment by s1hofmann** [comment]
@ricardopolo I just did a double check on Windows, it works just fine.
The only difference is that `mouse.drag` in nut.js actually performs a smooth drag, so the right way to do it is:

- Press and hold the correct mouse button
- Set mouse position
- Release the mouse button

See the following snippet:

```js
const {mouse, Button, sleep} = require("@nut-tree/nut-js");

(async () => {
        await sleep(3000);
        const current = await mouse.getPosition();
        await mouse.pressButton(Button.LEFT);
        await mouse.setPosition({x: current.x + 500, y: current.y});
        await mouse.releaseButton(Button.LEFT);
})();
```
