### ISSUE TITLE
keyboard.type takes too long

### ISSUE THREAD

**Issue by sminder** [nut-tree/nut.js#379]
**Short overview**

keyboard.type a long text takes too long, is there any way to speed up?

**Comment by s1hofmann** [comment]
Hi @sminder 👋 

The delay between keypresses is configurable: https://github.com/nut-tree/trailmix/blob/master/packages/keyboard-test/README.md#autodelayms

**Comment by sminder** [comment]
@s1hofmann thanks a lot!
