### ISSUE TITLE
Synchronous keyboard.type

### ISSUE THREAD

**Issue by dan-8888** [nut-tree/nut.js#380]
I need to have a **synchronous** keyboard type. At the moment, it is only async with:
await keyboard.type("calculator"); 

https://nutjs.dev/docs/api/keyboard/

@s1hofmann any idea how we can do it ? or does it need a change in nut.js ?

**Comment by s1hofmann** [comment]
Hi @dan-8888 👋 

nut.js is async by default, so this is not possible without changes.
