### ISSUE TITLE
Unable to open run command

### ISSUE THREAD

**Issue by code-drunk-debug-sober** [nut-tree/nut.js#385]
Hi,

I am trying to open the run command on Windows 10. 

I am sending the key event of 91 ( windows key ) + 81 ( character R ) but unable to.

Tried different combinations but seems like only the windows key is not responding to the key commands.

Can you please suggest anything ?

Thanks.

**Comment by s1hofmann** [comment]
Hi @code-drunk-debug-sober 👋 

could you please post a code snippet of what you've been trying so far?

Best regards

Simon

**Comment by s1hofmann** [comment]
Closed due to inactivity, feel free to reopen
