### ISSUE TITLE
mouse move issues, blocking input

### ISSUE THREAD

**Issue by slauko** [nut-tree/nut.js#386]
Hey just wanna ask if its normal that somehow my userInput gets blocked while i use mouse.move or mouse.setPosition in a fast loop ..
(like sometimes i cant leftclick manually while mouse is moving)
 
Also: when i wanna set the mousePos direktly to a position with setPosition the mouse still "slides" slowly to the pos instead intantly getting set ?

EDIT: its also blocking the whole program flow while moving the mouse .. like im running it in an async function besides my renderer and render stops/gets blocked while mouse is moving 😨

**Comment by slauko** [comment]
hi @s1hofmann 

oh ye ofc i coudl add those
currently dont have setup a repo for it just testing stuff out locally

windows11 21H2 (build 22000.556)
node 16.14
electron 17.1.2

basically calling this in an async function in a loop 
`
let closest = aimPositions[minIndex];
		if (minDistance < settings.aim.fov) {
			let diff = { x: closest.x - center.x, y: closest.y - center.y };
			if (aks.getAsyncKeyState(settings.aim.aimkey.value)) {
				let mousePos = await mouse.getPosition();
				let aimPos = new Point(mousePos.x + diff.x, mousePos.y + diff.y);
				await mouse.move(straightTo(aimPos));
				continue;
			}
		}
`

position is correct and it works well so far, besides that my whole drawings stopping till the movement is finished 

just doing await new Promise((r) => setTimeout(r, 1000)); in same place without calling mouse.move doesnt freezing my other code ..

**Comment by s1hofmann** [comment]
The underlying implementations are not yet 100% async, so some of them are blocking.

Overall, this sounds like you're doing all your processing in your render process?
To not block your render process you should move your workload to the main process and make use of IPC (e.g. [`ipcMain.handle`](https://www.electronjs.org/docs/latest/api/ipc-main/#ipcmainhandlechannel-listener))

**Comment by slauko** [comment]
Nono I do all my processing already in the ipcMain process, and sending calculated stuff to the ipcRenderProcess with send/on etc. 

But I do the mouse move stuff also in the ipcMain so the drawings doesnt get "updated" positions I guess 😅
