### ISSUE TITLE
Set a image or NSView/UIView/CoreGraphics.Line on the macOS screen rather than "get" (screen.find)

### ISSUE THREAD

**Issue by HaloWang** [nut-tree/nut.js#402]
**Short summary**

I'd like to draw a rectangle just like "border: 1px solid red" on the screen in macOS. I know nut.js doesn't support this feature yet, But can I do this in node.js (only a terminal without any GUI)?

**For example**

```js
// Something like this in node.js running on macOS or Windows
screen.draw({x, y, width, height, color: "#ff0000", borderWidth:1})
```

**Comment by s1hofmann** [comment]
Hi @HaloWang 👋 

I’m not sure whether I understand your question fully.

You want to draw a rectangle on screen? Only its border with no fill color?

If it’s not a hard requirement to only draw the outline, what about using [`screen.highlight`](https://nut-tree.github.io/apidoc/classes/screen_class.ScreenClass.html#highlight)?

**Comment by HaloWang** [comment]
> Hi @HaloWang 👋
> 
> I’m not sure whether I understand your question fully.
> 
> You want to draw a rectangle on screen? Only its border with no fill color?
> 
> If it’s not a hard requirement to only draw the outline, what about using [`screen.highlight`](https://nut-tree.github.io/apidoc/classes/screen_class.ScreenClass.html#highlight)?

🎉 YES! This is what I want (after I read it implementation). Thanks a lot!

**Comment by s1hofmann** [comment]
There's even a tutorial section for [`screen.highlight`](https://nutjs.dev/docs/tutorial-screen/highlight)

Haven't thought about pub.dev yet. Are you on the nut.js discord? Feel free to ping me there if you want to talk about it
