### ISSUE TITLE
Keys are not pressed in the automated tests during the Jenkins execution

### ISSUE THREAD

**Issue by andrii-solaris** [nut-tree/nut.js#406]
**Version**
2.1.1

**Short overview**
-- The tests are executed for the electron desktop application on the Jenkins node.  
-- The OS on which it is executed is Win10
-- The keys are pressed perfectly fine on non-Jenkins executions for Win10 and macOS

**Issue occurs on**
- Jenkins

**Detailed error description**
- No errors are thrown to the console

**Additional content**
Code example of usage: 
   const { Key, keyboard } = require('@nut-tree/nut-js')

    async pressAndHoldHotKey (time = 1000) {
        await keyboard.pressKey(Key.T)
        await keyboard.pressKey(Key.LeftControl)
        await new Promise(resolve => setTimeout(resolve, time))
        await keyboard.releaseKey(Key.LeftControl)       
        await keyboard.releaseKey(Key.T)      
    }

**Comment by s1hofmann** [comment]
Hi @andrii-solaris 👋 

given that everything works smoothly outside on non-Jenkins hosts I'm assuming a problem with how your Jenkins node is set up/configured.
Do you have access to the node to run the test manually?

Otherwise I can't do much as I don't now your environment.

**Comment by ivan-horchakov** [comment]
@s1hofmann you closed that issue pretty fast, aren't you? ;) 
Yes, we have access to the node to run the test manually. Please, help with this issue if you can. If you need additional info about our environment - I'll send it. TIA!

**Comment by s1hofmann** [comment]
@ivan-horchakov It’s does not seem to be related to nut.js, since it’s running fine on other machines.

**Comment by ivan-horchakov** [comment]
> @ivan-horchakov It’s does not seem to be related to nut.js, since it’s running fine on other machines.

We will review env setup, thanks!
