### ISSUE TITLE
Window.title()  from getActiveWindow  return garbled character when title has Chinese character

### ISSUE THREAD

**Issue by ouchuji** [nut-tree/nut.js#407]
**Version**
2.1.1
**Short overview**

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [ -] Dev/Host system

**Detailed error description**
```
    const current = await getActiveWindow()
    const title = await current.title
```
title would return  `ƴ��๤��`, but acutal is `拼多多工作台`

**Steps to reproduce error**
A window tile wich contains a Chinese character。
You can test get window title of this page `https://zhidao.baidu.com/question/25207546.html`

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @ouchuji 👋 

I can confirm that this is a problem.
Unfortunately nut.js is not properly supporting unicode yet.

**Comment by ouchuji** [comment]
OK @s1hofmann  , and how can I get `@NUT-TREE/NL-MATCHER` ?  I can not find it at the npm

**Comment by s1hofmann** [comment]
@ouchuji It’s a private package for sponsors. See https://nutjs.dev/plugins/imagefinder and https://github.com/sponsors/s1hofmann

**Comment by ouchuji** [comment]
@s1hofmann I am a sponsor now, and how can I get it? You need to set something?

**Comment by ouchuji** [comment]
OK, Thanks

**Comment by s1hofmann** [comment]
Closed in `@nut-tree/bolt` plugin.
