### ISSUE TITLE
Searching for a text color?.

### ISSUE THREAD

**Issue by jhemmmm** [nut-tree/nut.js#417]
Hello,

There's this game that I'm trying to create a macro/automation using nut.js, I'm trying to search for the color of the text which has color transparency. So getting the exact pixel color and checking it is kinda impossible. For example, the color of the text is "RED", sometimes it becomes, "DARK RED, LIGHT RED" because of the background of the text, Is there any possible way to check that?.

**Comment by s1hofmann** [comment]
If I understand this correct you're trying to locate the position of the text, but since it's not fully opaque it's hard to reliably detect via image template, right?

**Comment by jhemmmm** [comment]
> If I understand this correct you're trying to locate the position of the text, but since it's not fully opaque it's hard to reliably detect via image template, right?

Exactly. Do you have any suggestions?.

**Comment by jhemmmm** [comment]
I fixed it by using tolerance and other way to get it done.
