### ISSUE TITLE
Question regarding keyboard.type on Linux

### ISSUE THREAD

**Issue by zephr4** [nut-tree/nut.js#418]
**Short summary**
I'm trying to test the functionality in a Linux environment. I'm trying to use "Key.LeftSuper" to open the start menu and then open an app in Ubuntu 22.04 LTS. However when I run my script, the keyboard.type() is applied within the terminal. Meaning the start menu is never opened.  

```

const { keyboard, Key } = require("@nut-tree/nut-js");

(async () => {
    try {
        keyboard.config.autoDelayMs = 500;
        
        await keyboard.type(Key.LeftSuper);
        await keyboard.type("google chrome");
        await keyboard.type(Key.Return);

    } catch (e) {
        console.error(e);
    }
})();

```

**Desired execution environment / tested on**
- [x] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**Detailed question**
Why is the keyboard.type() command being applied only within the terminal and not interacting with the desktop?

**Comment by s1hofmann** [comment]
Hey @zephr4 👋 

I'm not 100% sure how this global, single key shortcut is handled, maybe that's a bit of an issue to simulate.
Using an alternative shortcut to open the application menu works flawless for me: https://share.cleanshot.com/7V0txh

**Comment by s1hofmann** [comment]
Closed due to inactivity.
