### ISSUE TITLE
3 high severity vulnerabilities

### ISSUE THREAD

**Issue by QimatLuo** [nut-tree/nut.js#422]
`npm i @nut-tree/nut-js@2.2.0`
Then we can see vulnerabilities dependencies.
Better to solve it.

![image](https://user-images.githubusercontent.com/9548054/187015809-407599c0-1fe5-42fd-8365-5655d73e3c67.png)

**Comment by s1hofmann** [comment]
Hi @QimatLuo 👋 

while we're waiting for an upstream fix I published a short advisory how users can mitigate these vulnerabilities in the meantime: https://nutjs.dev/blog/jimp-security-advisory

**Comment by QimatLuo** [comment]
Works for me.
Should I close this issue now? or just wait for the upstream fix then close this issue?

**Comment by s1hofmann** [comment]
You can keep it open, I'll close it once it's fixed upstream
