### ISSUE TITLE
Cannot install thru npm/yarn: registry not found

### ISSUE THREAD

**Issue by hecmay** [nut-tree/nut.js#428]
**Version**
Node 17.17.0
MacOS

**Short overview**
Cannot 

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

```shell
npm ERR! code E404
npm ERR! 404 Not Found - GET https://registry.npmjs.org/@nut-tree/nl-matcher-darwin/-/nl-matcher-darwin-1.0.1-next.20211202095927.tgz - Not found
npm ERR! 404 
npm ERR! 404  '@nut-tree/nl-matcher-darwin@https://registry.npmjs.org/@nut-tree/nl-matcher-darwin/-/nl-matcher-darwin-1.0.1-next.20211202095927.tgz' is not in this registry.
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.
```

**Steps to reproduce error**
```shell
npm i @nut-tree/nut-js
```

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hey @hecmay 👋 

this is not an actual error.

`@nut-tree/nl-matcher` is a sponsors-only package, so you don’t have access to this package.

Do you have a link to the `package.JSON` you’re installing from?

**Comment by hecmay** [comment]
@s1hofmann oh. I see. I thought that was a dep. thanks for explaining that 

I was trying to run this example: https://github.com/nut-tree/trailmix/tree/master/packages/electron-sample

**Comment by s1hofmann** [comment]
Ah, thanks for the info. I’ll update the sample to avoid this problem 👍

**Comment by jamninetyfive** [comment]
I have sponsored then how to use it.
