### ISSUE TITLE
Procedure could not be found (Redistributable issue)

### ISSUE THREAD

**Issue by fttx** [nut-tree/nut.js#429]
**Version**

- 64-bit Windows 8.1
- nutjs: ^2.2.0
- Redistributable seems to be installed but it's the x86 version. Maybe this is the cause of the issue

**Short overview**

Hi there,

a user is reporting the attached error when the electron app is launched: 

**Additional content**
![image](https://user-images.githubusercontent.com/5663423/189380221-a52b4b28-f5f9-49f0-b34f-2344518aa3f3.png)

**Comment by s1hofmann** [comment]
Hi @fttx 👋 

this is an OS problem.

nut.js, or more specifically libnut, uses functionality to deal with display scaling and high DPI displays that is only available since Windows 10, version 1607.

I’ll point this out in the docs.

**Comment by fttx** [comment]
Hey,

So is Windows 8 unsupported as well? Or it occurs only when there is a specific setting active?
What's the minimum required Windows version for nutjs to be 100% compatible?

Thank you

**Comment by s1hofmann** [comment]
Minimum Windows requirement:

Windows 10, version 1607, 64bit 

For Windows 10 N there’s an [additional requirement](https://github.com/nut-tree/nut.js#windows)

**Comment by fttx** [comment]
Hey, 

a user is reporting a similar issue on Windows 11:

![IMG_20221211_201623](https://user-images.githubusercontent.com/5663423/207067260-f070e156-5994-4a54-9cd7-864e1576aaf6.jpg)
