### ISSUE TITLE
Exited with SIGSEGV when keyboard.type on macOS

### ISSUE THREAD

**Issue by e-jigsaw** [nut-tree/nut.js#430]
**Version**
2.2.1-next.20220831203906

**Short overview**
Exited with SIGSEGV when to use keyboard.type with some chars like Key.C, Key.Q.

**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
I noticed with Electron app. But just nodejs also exit with Segmentation fault.

```js
"use strict";

const {keyboard, Key} = require("@nut-tree/nut-js");

describe("Keyboard test", () => {
    it("should open Spotlight on macOS", async () => {
        await keyboard.type(Key.LeftSuper, Key.Space);
        await keyboard.type("calculator");
        await keyboard.pressKey(Key.Return);
        await keyboard.releaseKey(Key.Return);
    });
});

```
=> works

from https://github.com/nut-tree/trailmix/blob/master/packages/keyboard-test/index.spec.js

```js
"use strict";

const {keyboard, Key} = require("@nut-tree/nut-js");

describe("Keyboard test", () => {
    it("should open Spotlight on macOS", async () => {
        await keyboard.type(Key.LeftSuper, Key.C);
    });
});

```
=> not works

```js
"use strict";

const {keyboard, Key} = require("@nut-tree/nut-js");

describe("Keyboard test", () => {
    it("should open Spotlight on macOS", async () => {
        await keyboard.type(Key.C);
    });
});

```
=> not works

```js
"use strict";

const {keyboard, Key} = require("@nut-tree/nut-js");

describe("Keyboard test", () => {
    it("should open Spotlight on macOS", async () => {
        await keyboard.type(Key.Q);
    });
});

```
=> not works

**Steps to reproduce error**

it just

```js
"use strict";

const {keyboard, Key} = require("@nut-tree/nut-js");

describe("Keyboard test", () => {
    it("should open Spotlight on macOS", async () => {
        await keyboard.type(Key.C);
    });
});
```

macOS 12.5.1
node 16.17.0

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @e-jigsaw 👋 

I'm currently on the road and only have macOS 12.5 at hand.
Here, I'm not able to reproduce but will give it another shot once I'm back home and have 12.5.1 to test in case that's causing a regression.

**Comment by e-jigsaw** [comment]
@s1hofmann 
Thank you for checking.

hmm...
By the way, which chipset did you verify? I'm using Apple M1 Max

**Comment by s1hofmann** [comment]
My development machine is an Intel Mac, but I’m also testing on an M1 Mac mini. But since I have to rent this additional hardware, that’s all I can do.

**Comment by Justin-van-der-Velden** [comment]
I'm having the same issue.

I'm running MacOS 13.6.3.

When I the file directly with `Bun 1.0.7` so like `bun run src/file.ts` it runs perfectly fine.
But whenever I call the function from another file it fails. For example I have a file with some standard function like:

`
import { myKeyboardFunction } from './src/file.ts'

export const awseomFunction = () => {
  myKeyboardFunction(someParams)
}
`

Getting `error: script "start" exited with code 11 (SIGSEGV)` and sometimes `error: script "start" exited with code 10 (SIGUSR1)`

**Comment by Justin-van-der-Velden** [comment]
I just fixed my issue by first doing a `pressKey` event.

Whenever I do a `pressKey` before `type` it works fine.
