### ISSUE TITLE
keyboard.type is inconsistent in typing and slows down cpu

### ISSUE THREAD

**Issue by sohelsd** [nut-tree/nut.js#432]
**Version**
2.3.0
**Short overview**
I am trying to use it with electron 15.3 and node 16. Keyboard typing is either too slow or very inaccurate (jumbles the letters) for a given phrase.
**Issue occurs on**
- [ ] Virtual machine
- [ ] Docker container
- [ x] Dev/Host system

**Detailed error description**
I am coming from Robotjs, and finally decided to migrate my app to Nut.js. For simple `keyboard.type('300 char long phrase')` it types inconsistently, jumbling the letters. I tried playing with `keyboard.config.autoDelayMs` 0 to 100 and none of them were consistently printing text as desired. Plus my CPU seems to be spiking when the program is running. I tried running both as promise and await mode and both yielded same result.
Additionally when the program is running, my trackpad which is set for touch to click changes to press to click. Touch to click opens context menu wherever I click.
**Steps to reproduce error**
- My environment is Apple M1 with macOS 12.5.
- electron 15.3 and node 16.14.1
- setTimeout to 5 seconds and execute keyboard.type('some long text') 
- Start the program and quickly click inside a Text field for program to run and print the text.

**Additional content**
> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @sohelsd 👋 

Could you please provide a link to a repo so I can reproduce this?

Thanks!

Best regards

Simon

**Comment by sohelsd** [comment]
Hi @s1hofmann it is unfortunately a private repo. But here's a basic sample I am trying to run and unable to get it to work
```
const {keyboard, Key } = require("@nut-tree/nut-js");
list = ["Node.js is a server-side javascript runtime environment that executes javascript instructions on a server and delivers the results to the web browser client. It runs on macOS, Windows, Linux, and other platforms.",
"If you’ve installed Node.js on your Mac to learn how it works, experiment using it on a server you run but no longer want it: you should uninstall it."]

keyboard.config.autoDelayMs = 10
exports.test = () => {
  list.forEach(async (l) => {
    await keyboard.type(l)
  });
}
```

**Comment by s1hofmann** [comment]
Hi @sohelsd,

the problem you're describing has nothing to do with nut.js, but is caused by your code.

`Array.prototype.forEach` is not asynchronous, so it calls each of the async callbacks but returns immediately.

The two async callbacks then both start to fill the keyboard input queue, leading to interleaved characters.

Something like

```js
const test = async () => {
  for (const sentence of list) {
    await keyboard.type(sentence);
  }
}
```

prints your text in order.
