### ISSUE TITLE
template-matcher 'Error: No ImageFinder registered'

### ISSUE THREAD

**Issue by AkamaiG** [nut-tree/nut.js#439]
template-matcher throws error Reason: 'Error: No ImageFinder registered'
adding does not solve the problem require("@nut-tree/template-matcher");

I use:
Electron: 13.0
@nut-tree/nut-js: 2.3.0
@nut-tree/template-matcher: 1.0.1

**Comment by s1hofmann** [comment]
Hi @AkamaiG 👋 

could you please provide a repo to check out or installation/application logs?

Best regards

Simon

**Comment by AkamaiG** [comment]
![image](https://user-images.githubusercontent.com/15989264/196888586-142f3919-4ecf-4bf8-886e-4ad490c78afa.png)
Not really sure how I can debug even further

Electron v13.6.9
Chromium v91.0.4472.164
Node v14.16.0v8 
v9.1.269.40-electron.0

https://nklayman.github.io/vue-cli-plugin-electron-builder/
I also use this, maybe it will give an understanding

**Comment by AkamaiG** [comment]
My console.log shows that the module (@nut-tree/template-matcher) is being initialized, but after I use "await screen.find(imageResource("OK.png"))", it throws an error that imageFinder is not registered

**Comment by s1hofmann** [comment]
Might depend on how the native dependencies are packaged.
Do you have a repo?
I don’t know this boilerplate, so I can’t tell without it

**Comment by AkamaiG** [comment]
I invited you to my Repo

**Comment by s1hofmann** [comment]
Not related to nut.js.

Your dependencies are not properly bundled (they are defined as [externals](https://webpack.js.org/configuration/externals/)), so they are not resolved.
