### ISSUE TITLE
Unable to respond when the window system is locked

### ISSUE THREAD

**Issue by hijulien** [nut-tree/nut.js#440]
**Version**

**Short overview**
lasted
**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**Detailed error description**

**Steps to reproduce error**

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @hijulien 👋 

Please provide a meaningful description and an outline what you’re trying to achive, not just an empty issue with only a title.

Feel free to reopen once you can provide more info.

Best regards 

Simon
