### ISSUE TITLE
'RightShift' key is mapped to space?

### ISSUE THREAD

**Issue by musab1234** [nut-tree/nut.js#442]
'RightShift' is mapped to space in code. See:
https://github.com/nut-tree/nut.js/blob/bc5e99c1f0ad405a4111ad4f861e05e968cd7140/lib/provider/native/libnut-keyboard.class.ts#L91

is there any specific reason or its just a mistake?

**Comment by s1hofmann** [comment]
Hi @musab1234 👋 

that’s a mistake, thanks for reporting!

Best regards

Simon
