### ISSUE TITLE
Errors in Electron >= v21 due to Memory Cage

### ISSUE THREAD

**Issue by raphaelmenges** [nut-tree/nut.js#453]
`version: 2.3.1-next.20221115224324`

Hi,

when calling [Screen.grabRegion](https://nut-tree.github.io/apidoc/classes/screen_class.ScreenClass.html#grabRegion) from Electron >= v21, following error is thrown:

> Fatal error in V8: v8_ArrayBuffer_NewBackingStore When the V8 Sandbox is enabled, ArrayBuffer backing stores must be allocated inside the sandbox address space. Please use an appropriate ArrayBuffer::Allocator to allocate these buffers.

I believe this is caused by the Electron feature ["Memory Cage"](https://www.electronjs.org/blog/v8-memory-cage), which [cannot be simply deactivated](https://github.com/electron/electron/issues/35241).

**Comment by s1hofmann** [comment]
Hi @raphaelmenges 👋 

here’s a related upstream issue https://github.com/nodejs/node-addon-api/issues/1227

Will keep track on this to see when it’ll land.

**Comment by raphaelmenges** [comment]
Thanks @s1hofmann for the swift reply and relevant pointer!

The Node/Electron world is so fastly evolving, it is difficult to keep track 🥴 Looking forward for a solution, because the newer Electron versions fix issues that are relevant for me otherwise 😣

**Comment by s1hofmann** [comment]
Should be fixed with [Electron release 21.3.4](https://releases.electronjs.org/release/v21.3.4)
