### ISSUE TITLE
Mouse position and movements not displaying properly

### ISSUE THREAD

**Issue by ARGON90** [nut-tree/nut.js#454]
### Hi all,
I'm just getting started and making my way through the docs. I was able to successfully install the module, but cannot get it to correctly print out mouse positions, or move the mouse around at all. I'm using WSL and Ubuntu 16.16.0.

per the docs, I tried this code:
```
const { mouse, left, right, up, down } = require("@nut-tree/nut-js");

(async () => {
    await mouse.move(right(500));
    await mouse.move(up(500));
    await mouse.move(right(500));
    await mouse.move(down(500))
})();
```
When executed, no movement occurs with my mouse. Also, when I try

` console.log(mouse.getPosition())` , it does not display my current position.

However, one clue is that my mouse position _console logs_ do change after using `mouse.move()` however, my _actual mouse position does not_ . It's almost like it's keeping track of an invisible mouse position, and moving that mouse around.

For example, 
```
    console.log(mouse.getPosition())
    await mouse.move(right(100));
    console.log(mouse.getPosition())
    await mouse.move(up(100));
    console.log(mouse.getPosition())
    await mouse.move(right(100));
    console.log(mouse.getPosition())
    await mouse.move(down(100))
    console.log(mouse.getPosition())
```
prints out:
```
Promise { Point { x: 1000, y: 510 } }
Promise { Point { x: 1100, y: 510 } }
Promise { Point { x: 1100, y: 410 } }
Promise { Point { x: 1200, y: 410 } }
Promise { Point { x: 1200, y: 510 } }
```
despite my mouse remaining exactly in the center of the screen the whole time.

 I'm curious if there are certain permissions I need to enable anywhere, or something like that.

Thanks for the help!

**Comment by s1hofmann** [comment]
Hi @ARGON90 👋 

Please see #288 for more info.

Could you please run your scripts in a Windows native shell like PowerShell?

Best regards 

Simon

**Comment by ARGON90** [comment]
Thanks @s1hofmann ! It works great. I should have realized that I'd have to do this with the native shell.

**Comment by s1hofmann** [comment]
> It works great

Perfect!

**Comment by freddy-daniel** [comment]
This problem is came back in native shell too
