### ISSUE TITLE
Add Context Menu Key

### ISSUE THREAD

**Issue by otelo2** [nut-tree/nut.js#457]
The context menu key performs the same action as the right click key but in the location of the keyboard cursor.
This key is currently missing from the Key enum.

Main use case for me is when I want to right click on some text that I'm writing, but it I can't know where the current text that I'm writing is located on the screen, and using template matching to find the blinking cursor doesn't work and causes false positives.
Adding the context Manu key will allow me to access the right click menu on the location I want without having to worry about finding the correct location.

I can provide more information as requested. Thank you.

**Comment by otelo2** [comment]
A workaround is to press shift+f10

**Comment by s1hofmann** [comment]
Published with release [v3.1.0](https://github.com/nut-tree/nut.js/releases/tag/v3.1.0)
