### ISSUE TITLE
Can arguments  to call keyboard.type() got injected to press unwanted button

### ISSUE THREAD

**Issue by ydhnwb** [nut-tree/nut.js#458]
**Short summary**
Is keyboard.type() able to be injected from a string?

**Desired execution environment / tested on**
- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed question**
Is keyboard.type() able to be injected? using like  "hello ^[[15~" ? While ^[[15~ supposed to press F2 key?
I just wondering and cannot have proper test to validate this.

**Comment by s1hofmann** [comment]
Hi @ydhnwb 👋 

Short answer: No, this is not possible.

Best regards

Simon
