### ISSUE TITLE
Are the prereqs required for end users who install my electron app as well?

### ISSUE THREAD

**Issue by himat** [nut-tree/nut.js#459]
Are the prereqs required for end users who install my electron app as well, or is that only required for me as the developer?
i.e. for macos, I have to run `xcode-select --install` before installing this package in my repo.
But for my electron app I'm making that uses this package, would my end users need to install xcode as well? That would be very difficult if so since the end users are not developers and wouldn't know how to install that.

**Comment by himat** [comment]
@s1hofmann do you know the answer to this?

**Comment by s1hofmann** [comment]
@himat It depends on your platform. Linux requirements have to be met on runtime systems as well, for Windows nut.js started shipping required files with v2.3.0.
On macOS you also shouldn’t have to install requirements on runtime systems, but I haven’t checked on a fresh install recently.
