### ISSUE TITLE
keyboard type function doesn't type entire string at once

### ISSUE THREAD

**Issue by himat** [nut-tree/nut.js#460]
It seems the nut.js keyboard type function doesn't type the entire string at once like the `robotjs` one did?
This is pretty inconvenient when you want to enter in an entire piece of text at once.

If you compare
```
keyboard.type('hi there');
```
vs 
```
robot.typeString('hi there');
```
The first one types char by char which takes a while, whereas the second inputs the entire string instantly into whatever text box you're in.

I saw that I can configure the delay for nut
`keyboard.config.autoDelayMs = 50;`
But that parameter is not working well. At 100, it types correctly, but if I lower it to 50, I saw the first character was missing, and if I lowered it to 10, many characters were not typed.

Is there a workaround for this that makes the typing equivalent to the robotjs way?

**Comment by s1hofmann** [comment]
Hi @himat 👋 

That shouldn’t be too hard to adjust.

Related: #409 

Best regards

Simon

**Comment by himat** [comment]
Thanks Simon

Yeah that would work for me for now. Although I don't like the idea of replacing what's in the user's clipboard though every time. So I think it would be more sustainable to be able to directly paste the entire text just like how pasting from the clipboard does it.

**Comment by s1hofmann** [comment]
Hi @himat 👋 

modifying the clipboard content is not ideal, yes, but if you really want to have instant pasting, this is the only way to go.
Lowering the keyboard delay to 0 will still type one character after another, I'm pretty sure this is no different in robot.js.

I'll have a look at the behaviour you described, though.

**Comment by himat** [comment]
@s1hofmann yeah I think you're right. 

But then is there a way to do what the clipboard pasting does of entering in an entire piece of text at once that can be replicated without saving to the clipboard?

**Comment by zaneschepke** [comment]
I have also noticed this same behavior. If I had delay set to 20 ms it skipped the first three characters of what I was trying to type. 

This is on Windows 11.

**Comment by Justiniscoding** [comment]
If you are planning to use the clipboard method to type the string all at once, you can store the initial value of the clipboard in a variable and then set it back to the initial value after your script is done executing

**Comment by s1hofmann** [comment]
Closed due to inactivity, feel free to re-open on updates.
