### ISSUE TITLE
Error when searching for image resource (`Error: MatchRequest: Parameter 'providerData' is not an object'`)

### ISSUE THREAD

**Issue by Planeshifter** [nut-tree/nut.js#468]
**Version**: 

    "@nut-tree/nl-matcher": "^2.0.0",
    "@nut-tree/nut-js": "^3.0.0"

The error occurs on all multiple Node.js versions I tested (v12,v15, v18.13.0).

**Short overview**

Running `screen.find` , `screen.findAll`, and `screen.waitFor` with an image resource (local or fetched remotely) errors for me with the following message:

```bash
Error: [nut.js] - Error: Searching for C:\Users\pb\Documents\GitHub\reproducible-error-reports\icon.png failed.
 Reason: 'Error: MatchRequest: Parameter 'providerData' is not an object'
```

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

The following Node.js script errors with the message that `Searching for <path>\icon.png failed. Reason: 'Error: MatchRequest: Parameter 'providerData' is not an object'`.

```js
const { screen, imageResource } = require('@nut-tree/nut-js');
require('@nut-tree/nl-matcher');

screen.config.resourceDirectory = __dirname;

(async () => {
	try {
		await screen.find( imageResource( 'icon.png' ) );
	}
	catch (err) {
		console.log( err );
	}
})();
```

**Steps to reproduce error**

1. Clone the following repository: https://github.com/Planeshifter/reproducible-error-reports
2. Run `npm install`
3.  Run `node screen_find_image.js`

You should see output similar to the following:
```bash
2023-01-17T23:37:41.595Z - INFO - [nut.js] - Searching for [object Object]
2023-01-17T23:37:41.600Z - DEBUG - [nut.js] - Running an image search
2023-01-17T23:37:41.660Z - DEBUG - [nut.js] - Running on-screen search with parameters {
  minMatch: 0.99,
  screenSize: Region { left: 0, top: 0, width: 1600, height: 1067 },
  searchRegion: Region { left: 0, top: 0, width: 1600, height: 1067 }
}
2023-01-17T23:37:41.664Z - INFO - [nut.js] - Searching for image C:\Users\pb\Documents\GitHub\reproducible-erro
r-reports\icon.png in region (0, 0, 1600, 1067). Required confidence: 0.99
2023-01-17T23:37:41.664Z - DEBUG - [nut.js] - Validating search region: (0, 0, 1600, 1067)
2023-01-17T23:37:41.664Z - DEBUG - [nut.js] - Search region is valid
Error: 2023-01-17T23:37:41.665Z - ERROR - [nut.js] - Error: Searching for C:\Users\pb\Documents\GitHub\reproduc
ible-error-reports\icon.png failed. Reason: 'Error: MatchRequest: Parameter 'providerData' is not an object'
    at ScreenClass.find (C:\Users\pb\Documents\GitHub\reproducible-error-reports\node_modules\@nut-tree\nut-js\
dist\lib\screen.class.js:144:27)
```
**Additional content**

-   Error seems to happen in L117 / L192 of the `screen.class.js` file of the `nut-js/dist/lib` folder:
`const matchResult = await (0, match_result_class_1.getMatchResult)(this.providerRegistry, matchRequest);`
or
`const matchResults = await (0, match_result_class_1.getMatchResults)(this.providerRegistry, matchRequest);`.
-   The error does not occur when using the other image finder, i.e. when requiring `@nut-tree/template-matcher` instead of `@nut-tree/nl-matcher`.

**Comment by s1hofmann** [comment]
Hi @Planeshifter 👋 

Thanks for the detailed error report 👍 

Seems like I messed up the optional parsing in my native bindings and didn't have a test for that.
I'll get it fixed.

For now, what you could simply pass an object like so:

```js
screen.find(imageResource("image.png"), {providerData: {searchMultipleScales: true}});
```

**Comment by s1hofmann** [comment]
A new snapshot release is out containing a fix.

`npm i @nut-tree/nl-matcher@next`

**Comment by Planeshifter** [comment]
Awesome, thank you for the quick turnaround!

**Comment by s1hofmann** [comment]
@Planeshifter `@nut-tree/nl-matcher@2.0.1` is available
