### ISSUE TITLE
Screen capture broken on macOS 13

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#469]
**Version**
3.0.0

**Short overview**
Grabbing screen content seems to be somewhat broken on macOS Ventura.

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
Grabbing screen content on macOS 13 does not throw an error, but instead of showing the full screen content it just shows an empty desktop

**Steps to reproduce error**
Use `screen.capture` to snap a screenshot, check its content

**Comment by jamninetyfive** [comment]
is that 3.1.2-next.20230310000145 ?

**Comment by s1hofmann** [comment]
> 

Yes

**Comment by yusukeiwabuchi** [comment]
@s1hofmann 
Hi,  Simon!

I have two questions.

I used @next but the image data is corrupted.
I tested at all resolutions and the results were the same.
(1024x640, 1280x800, 1440x900, 1680x1050)
Is there any workaround?

MacBook Pro 13 inch
OS: Ventura 13.1
CPU: Apple M2


When is this bug expected to be fixed?
I don't mean to rush you.

**Comment by jamninetyfive** [comment]
same~

**Comment by chan-shiro** [comment]
@s1hofmann 

Thanks, now fullscreen screen capture works fine, but, output image of captureRegion is still corrupted.

Any suggestion?

MacBook Pro 13 inch
OS: Ventura 13.1
CPU: Apple M2

**Comment by s1hofmann** [comment]
There's now a workaround implemented that's available for testing in `@nut-tree/bolt@next` (sponsors only for now)

https://share.cleanshot.com/Df4npQ0c

/cc @chan-shiro @yusukeiwabuchi

**Comment by yusukeiwabuchi** [comment]
@s1hofmann 

Thank you for your response!
However, I still have a problem...

I cannot take pictures of objects (folders, app icons) and Dock that are present on the desktop.

Actual screen
<img width="500" alt="スクリーンショット_2023-04-13_12_15_03" src="https://user-images.githubusercontent.com/29683756/231640703-33427d6b-dd71-4876-918f-3b88f7b7600b.png">

screen.capture
<img width="500" alt="スクリーンショット_2023-04-13_12_15_03" src="https://user-images.githubusercontent.com/29683756/231640714-11373cab-3355-49d3-bf6b-dd87f0f74574.png">

screen.captureRegion

<img width="500" alt="スクリーンショット_2023-04-13_12_15_03" src="https://user-images.githubusercontent.com/29683756/231640722-97aa82c3-5ff3-42ff-ba34-47230dc0733f.png">

**Comment by yusukeiwabuchi** [comment]
@s1hofmann 

Sorry.
I did not give permission to VSCode for screen recording.

I have confirmed that it works properly. Thank you very much!

**Comment by s1hofmann** [comment]
> @s1hofmann
> 
> Sorry. I did not give permission to VSCode for screen recording.
> 
> I have confirmed that it works properly. Thank you very much!

I was just about to write this 😃 

So can you confirm the fix works as expected?

**Comment by yusukeiwabuchi** [comment]
I have confirmed that screen.capture and screen.captureRegion work as expected.

**Comment by s1hofmann** [comment]
Implemented in https://github.com/nut-tree/nut.js/releases/tag/v3.1.2
