### ISSUE TITLE
Creating a new Jimp instances looses data

### ISSUE THREAD

**Issue by s1hofmann** [nut-tree/nut.js#470]
**Version**
3.0.0

**Short overview**
Even though screen content is grabbed correctly, Jimp fails to create a new instance using the data buffer

**Issue occurs on**

macOS Ventura

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
https://github.com/oliver-moran/jimp/issues/932

**Comment by kele6ra** [comment]
Hello, it is not the error, that you mentioned. 
It appears only in macOS Ventura. I have checked it with win11 and ubuntu20, and macOS Monterey.
Venture returns not valid raw image (it looks like image bigger that width*height) and Jimp doesn't create object because of it.

**Comment by s1hofmann** [comment]
Hi @kele6ra 👋 

Were you able to reproduce said behavior on Ventura?
I tested both of my development machines (Intel MBP, macOS 13.2, Mac Mini M1 macOS 13.1) and I wasn’t able to reproduce this error on any of it.

**Comment by kele6ra** [comment]
I am mentor in nodeJS courses. And my students with macOS 13+ use this code to get region image. After img.toRGB they receives `Error: w and h must be numbers`. img.data from win11. linux and macos 12 is converted without any problems. After I compare them I have found that buffer from macos13+ is not valid for the new Jimp call.
`         const region = new Region(position.x, position.y, 200, 200);
          const img = await screen.grabRegion(region);
          const imgRGB = await img.toRGB();
          const imgJimp = new Jimp ({
            data: imgRGB.data,
            width: imgRGB.width,
            height: imgRGB.height
          });
`

**Comment by kele6ra** [comment]
We loose our buffer here
https://github.com/nut-tree/nut.js/blob/develop/lib/provider/io/imageToJimp.function.ts
And after we have empty w and h parameters

**Comment by s1hofmann** [comment]
I identified this as well, maybe you could collect detailed infos about the systems where this occures? (Exact macOS version, architecture, screen resolution, are external displays connected, node version)

**Comment by kele6ra** [comment]
I have asked my students to write theirs PC specs and env configs here.

**Comment by KateKaliaha** [comment]
> I identified this as well, maybe you could collect detailed infos about the systems where this occures? (Exact macOS version, architecture, screen resolution, are external displays connected, node version)
MacOS version - Ventura 13.1,
architecture - ARM,
screen resolution 13,3 inch (2560×1600)
aren't external displays connected 
node version -v18.12.1

**Comment by TheLevius** [comment]
Macbook Air M1,
MacOS Ventura 13.2,
node 18.12.1
2560x1440 (OS scale to 1680x1050)

**Comment by s1hofmann** [comment]
So far this seems to only happen on Retina display Apple Silicon MacBooks 🤔

**Comment by s1hofmann** [comment]
Hi @KateKaliaha and @TheLevius 

could you please post the output of the following snippet?

```js
const {
  screen,
} = require("@nut-tree/nut-js");

(async () => {
  const img = await screen.grab();
  const bufferSize = img.data.length;
  const channels = bufferSize / (img.width * img.height);
  console.log({bufferSize});
  console.log({width: img.width, height: img.height});
  console.log({channels});
})();
```

**Comment by jamninetyfive** [comment]
any updates?

**Comment by jamninetyfive** [comment]
move jimp to sharp maybe?

**Comment by s1hofmann** [comment]
@jamninetyfive My biggest problem is that I still can’t reproduce this issue on any of my machines, thus I still don’t have a clue about the root cause.
So I also can’t tell if switching the image processing library would actually change anything.

My last straw is to see if I can get an Apple Silicon MacBook that doesn’t cost a fortune to figure out what’s going on.

**Comment by reymundolopez** [comment]
@s1hofmann since you got no response from the script you asked, here is mine: 
```
{ bufferSize: 43888896 }
{ width: 4112, height: 2658 }
{ channels: 4.01556420233463 }
```
MacBook Pro 16" M1 Pro
Screen: 16-inch (3456 x 2234)
OS 13.1
Node: 18.12.1
Hope that helps!

**Comment by s1hofmann** [comment]
Hi @reymundolopez 👋 

Thanks for posting your output, it is the final confirmation I've been looking for!

It clearly shows that the image data is a bit messed up since the data returned is in fact larger than the expected image data. (That is width*height*4 channels).

So instead of the expected 4 channels we get `4.01556420233463` which throws off Jimp.

Could you maybe post the output of the above snippet again, after installing `@nut-tree/nut-js@next`?

Additionally, you could try running 

```js
const {
  screen,
} = require("@nut-tree/nut-js");

(async () => {
  await screen.capture("test.png");
})();
```

again using the latest snapshot `@nut-tree/nut-js@next`

Thanks for your help!

All the best

Simon

**Comment by reymundolopez** [comment]
@s1hofmann this is the output:

```
"@nut-tree/nut-js": "^3.1.2-next.20230310000145",
```
```
{ bufferSize: 43718784 }
{ width: 4112, height: 2658 }
{ channels: 4 }
```

![test](https://user-images.githubusercontent.com/226329/224357693-3028677b-89e3-4ab0-975a-61f8188b5542.png)

**Comment by s1hofmann** [comment]
Ok, this seems to be a similar situation as with https://github.com/nut-tree/libnut-core/issues/44 a few years ago 🙈

**Comment by s1hofmann** [comment]
@reymundolopez I'm assuming you're using a scaled resolution? Could you try running the snippet using the default resolution?

**Comment by reymundolopez** [comment]
@s1hofmann you are correct, my display was scaled.

Here are the results using the default screen resolution:
```
"@nut-tree/nut-js": "^3.1.2-next.20230310000145",
```

```
{ bufferSize: 30882816 }
{ width: 3456, height: 2234 }
{ channels: 4 }
```
![test](https://user-images.githubusercontent.com/226329/226757023-5cc9d071-fe2e-4432-b954-e18a20e9c5b2.png)

**Comment by s1hofmann** [comment]
I filed a bug report with Apple about this issue.

Reproducibly happens specifically on Apple Silicon + Ventura.
Returned image data is 1024 bytes larger than expected, which it wasn't on Monterey.

I'll keep this issue updated.

**Comment by s1hofmann** [comment]
Have a look at https://github.com/nut-tree/nut.js/issues/469#issuecomment-1479273830 for a workaround

**Comment by s1hofmann** [comment]
Closing in favour of #469
