### ISSUE TITLE
Integration into tauri vue3 template to use error reporting

### ISSUE THREAD

**Issue by muyaCode** [nut-tree/nut.js#475]
**Version**
3.0.0

**Short overview**
An error occurs after the module is installed

**Issue occurs on**
The error is as follows:

![1676024203016](https://user-images.githubusercontent.com/48587992/218066397-5bc79845-ccd4-42e9-ac6f-0f553ff3aeee.jpg)

X [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@jimp/custom". The package may have incorrect main/module/exports specified in its package.json.

X [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@jimp/types". The package may have incorrect main/module/exports specified in its package.json.

X [ERROR] [plugin vite:dep-pre-bundle] Failed to resolve entry for package "@jimp/plugins". The package may have incorrect main/module/exports specified in its package.json.

...

**Comment by s1hofmann** [comment]
As per [this discussion](https://github.com/tauri-apps/tauri/discussions/2592) node packages aren’t usable with Tauri
