### ISSUE TITLE
Querying and manually requesting permissions for Electron applications on Mac.

### ISSUE THREAD

**Issue by mushan0x0** [nut-tree/nut.js#477]
**Short overview**

I want to trigger permission requests manually, so that I can better guide users to set permissions.

**Detailed feature description**

```ts
const Permission = {
  /**
   * Query whether the user has a certain permission
   * @param {string} permissionName - The name of the permission
   * @returns {boolean} - Whether the user has the permission
   */
  query(permissionName) {
    // Implement query logic
  },
  
  /**
   * Request a certain permission
   * @param {string} permissionName - The name of the permission
   * @returns {Promise<boolean>} - A Promise that resolves if the permission is granted, and rejects if the permission is not granted
   */
  request(permissionName) {
    // Implement request logic
  },
}
```

**Comment by s1hofmann** [comment]
Hi @mushan0x0 :wave:

since this would be specific to macOS only I’d rather not add it to the core framework.
Instead, I’d suggest using https://github.com/nut-tree/node-mac-permissions directly.

Best regards 

Simon

**Comment by mushan0x0** [comment]
Thank @s1hofmann 

But now whenever I run the program, it automatically jumps to the permission settings section. Can I control it manually?

**Comment by s1hofmann** [comment]
> Can I control it manually?

You mean explicitly disabling this behaviour? No.
The automated permissions check runs as soon as you call a function requiring e.g. accessibility and/or screen recording permissions.
An example would be `keyboard.type`

**Comment by mushan0x0** [comment]
@s1hofmann 

I used the `keyboard.pressKey` method in my program, but when I opened the program, this method was not called. 
However, the system authorization interface was still displayed, which prevented me from guiding the user to the settings.
Normally, the authorization interface should be displayed only when this method is called?

**Comment by s1hofmann** [comment]
I just noticed two methods requesting permissions that actually do not need them, I'll update that.

Regarding https://github.com/nut-tree/nut.js/issues/476, have you removed the application from your permissions list yet?
It might be the case that you granted permissions once, but when you re-package your application, the permission check can't cope with it.

**Comment by mushan0x0** [comment]
@s1hofmann 

I used the `keyboard.pressKey` and `keyboard.releaseKey` APIs. It would be great if no authorization is needed for them, as this would greatly reduce the usage threshold. Thank you very much.

Regarding issue #476, it always exists on my computer. Even after removing and adding it again, it still has the same problem. However, when I installed it on another computer, there was no problem.

**Comment by s1hofmann** [comment]
These two methods definitely require accessibility permissions to work, so they can't be removed.

**Comment by s1hofmann** [comment]
Hi @mushan0x0 👋 

I just spent some more time on this topic since it kept circling in my head.
There’s indeed a bug that leads to the permissions dialog being shown eagerly.

I’ll work on that.
Sorry if I sounded harsh, I was at fault here.

Best regards

Simon
