### ISSUE TITLE
Keyboard should have a function that allows you to listen for keypress events

### ISSUE THREAD

**Issue by zaneschepke** [nut-tree/nut.js#479]
**Short overview**
Keyboard should allow you to listen for user keypress events

**Use case**
This would allow users of nutjs to be able to trigger different automated flows based on keypress events/macros/etc.

**Detailed description**
Add a method to keyboard that has a callback in which users can see keypress events by user.

**Comment by Justiniscoding** [comment]
I agree, this would be a really useful feature, especially when making a script that relies on user input to trigger different automations

**Comment by s1hofmann** [comment]
Mouse and keyboard event monitoring will soon land in nut.js

**Comment by s1hofmann** [comment]
Available in v4.5.0 with `@nut-tree/bolt@2.2.0`

https://nutjs.dev/blog/release450
