### ISSUE TITLE
Docker: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by david-tejada** [nut-tree/nut.js#482]
**Version**
3.0.0

**Short overview**
I get an error when I try to use nutjs in a docker container. Running in an m1 mac if that's any help. I'm new to docker so I may have made a mistake.

**Issue occurs on**

- [ ] Virtual machine
- [x] Docker container
- [ ] Dev/Host system

**Detailed error description**
```
/app/node_modules/bindings/bindings.js:121
        throw e;
        ^

Error: /app/node_modules/@nut-tree/libnut-linux/build/Release/libnut.node: cannot open shared object file: No such file or directory
    at Module._extensions..node (node:internal/modules/cjs/loader:1338:18)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at bindings (/app/node_modules/bindings/bindings.js:112:48)
    at Object.<anonymous> (/app/node_modules/@nut-tree/libnut-linux/index.js:5:33)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32) {
  code: 'ERR_DLOPEN_FAILED'
}

Node.js v18.14.2
```
**Steps to reproduce error**
I created a minimal repro example: https://github.com/david-tejada/nutjs-docker
```
docker build --tag nutjs-docker .
```
```
docker run nutjs-docker
```

**Comment by s1hofmann** [comment]
Hi @david-tejada 👋 

your Dockerfile is fine, I'd assume the error you posted was caused by an erroneous image build.

However, I'll have to disappoint you that you wont be able to use nut.js with an image like the `node:18` one.
This image has no running X server, which is required for nut.js to perform its tasks. (The copy/paste mechanism is provided by X as well)
Try using an image with a built-in X server instead.

All the best

Simon

**Comment by david-tejada** [comment]
Thanks for the quick response. In my actual project I'm actually using xvfb based off of this: https://github.com/mujo-code/puppeteer-headful. I actually have puppeteer headful working in the docker container and all my test run ok except the one that uses nutjs. But maybe this is not enough to run nutjs?

**Comment by s1hofmann** [comment]
Just gave the linked image a try and used it as base for your provided test. Works out of the box without errors.

**Comment by s1hofmann** [comment]
@david-tejada So to wrap up your question: The `headful` puppeteer image is missing libXtst, so running the plain base image will fail.
But you could create your own fork to extend it accordingly.

**Comment by david-tejada** [comment]
Thanks, that works in the GitHub action. I don't know why it wasn't working locally
