### ISSUE TITLE
Umlaute and emoji typing broken (Windows 10)

### ISSUE THREAD

**Issue by raphaelmenges** [nut-tree/nut.js#483]
Hello 👋

I was successfully using the `keyboard.type` functionality to type both German umlauts and emojis in Windows 10 (#283). Recently, it seems to have stopped working. I have already checked different version of `nut.js`, namely `2.3.1-next.20221115224324`, `3.0.0`, and `3.0.1-next.20230217194627`, and both Node.js 16 LTS and Node.js 18 LTS. Apparently, it does not work on my Windows machine with update level `22H2`, but it still works on another laptop with update level `20H2`. Thus, I assume something happened to the Windows API?

You could use my minimal example [here](https://github.com/raphaelmenges/SimpleKeyEmulation) to hopefully reproduce the issue.

Expected output to a focused editor: `abcäüö🤣`
Actual output to a focused editor: `abc#`

I am also grateful for hints how to resolve the issue temporarily, e.g., by using an alternative appraoch for typing umlaute and emojis!

**Comment by s1hofmann** [comment]
Hi @raphaelmenges 👋 

As a consequence of https://nutjs.dev/blog/money unicode support did not ship with 3.0.0 but instead was moved to https://nutjs.dev/plugins/bolt

So the available options would be:

1. Sponsor my work
2. To stay on an old beta 
3. Translate unicode into keyboard shortcuts 

All the best 

Simon

**Comment by raphaelmenges** [comment]
Thank you @s1hofmann for the swift reply!

> 2\. To stay on an old beta

Apparently I remember `2.3.1-next.20221115224324` to work for me but nowadays it does not. Could you point out to the latest version that should work to type unicode?

**Comment by s1hofmann** [comment]
Hey @raphaelmenges 👋 

I just verified a Windows 10 system with update level `22H2`, which works flawlessly.
Since the APIs in use are stable since decades you must have mixed up versions.

Best regards 

Simon
