### ISSUE TITLE
Accented characters don't work on windows

### ISSUE THREAD

**Issue by MariaCamilaCubides** [nut-tree/nut.js#484]
**Version**
3.0.0

**Short overview**
I used the function type from keyboard and the function works as expected in macOS but when I tested on Windows it failed. 
I tried to type the string "áéíóú", for that I used `keyboard.type("áéíóú")`

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**
In windows 11 no character appears when the code is run

**Steps to reproduce error**
Use `keyboard.type("áéíóú")` in windows

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by raphaelmenges** [comment]
Perhaps related to #483?

**Comment by s1hofmann** [comment]
> Perhaps related to #483?

Exactly
