### ISSUE TITLE
how to drag a file to a new position on windows 11?

### ISSUE THREAD

**Issue by mankeheaven** [nut-tree/nut.js#492]
I can drag my app to a new position with code like this.
```
import { mouse, straightTo, Point } from "@nut-tree/nut-js";
mouse.config = {
	autoDelayMs: 80,
	mouseSpeed: 3000,
};

const main = async ()=> {
  const pos = new Point(535/1.5, 345/1.5); //The position is right
  await mouse.setPosition(pos)
  await mouse.pressButton(0);
  const target = new Point(535, 345);
  await mouse.drag(straightTo(target));
  await mouse.releaseButton(0);
}

main()
```
I don‘t know how to drag window's file to a new position in desktop. Is there any problem with my code?

![image](https://user-images.githubusercontent.com/17426397/225807151-cd07a8c1-d0b2-490a-b137-407a9fb6f6de.png)

**Comment by s1hofmann** [comment]
Hi @mankeheaven 👋 

You don't need to explicitly press/release mouse buttons, `mouse.drag()` takes care of that.
Alternatively, you can press/release the mouse button yourself and move the mouse via `mouse.move()`.

Other than that, your code is fine and it also works as expected, verified on my Windows 10 test VM.

All the best

Simon

**Comment by mankeheaven** [comment]
Thank you for you help， @s1hofmann .
Yes, it works well on my Windows 10.  It does not work on my Windows 11.
```
  await mouse.pressButton(0);
  const target = new Point(535, 345);
  await mouse.move(straightTo(target));
  await mouse.releaseButton(0);
```
Windows 11 is strange, let me describe the bug I encountered.

**I can not drag file on my desktop，I can open the context menu but i can't click the refresh button or other button, but I can click the button in my vscode or other app。**

My operating system information is as follows.

![image](https://user-images.githubusercontent.com/17426397/226075432-b410edc6-9119-4e52-bc5e-aafb4e0ac2d9.png)

I have no idea about windows 11.

**Comment by s1hofmann** [comment]
I'm unable to reproduce this issue, so for now I'm closing it due to inactivity.

If this problem persists, feel free to reopen.
