### ISSUE TITLE
Please include Arm64 Support (Apple Silicon M1) for template-matcher

### ISSUE THREAD

**Issue by DamonMedek** [nut-tree/nut.js#494]
**Short overview**
npm i @nut-tree/template-matcher
Won't install on my Mac. Seems like a huge feature that I can't use. More Mac users are moving to the M1 chip quickly because its performance is a lot better. I think adapting this should be a huge priority. Also I'd love it. 
I'm not great with NPM other than basic install and uninstalls. I'd prefer a fix than a work around. 

> Please provide any (mandatory) additional data for your enhancement

**Comment by s1hofmann** [comment]
Hi @DamonMedek 👋 

> I think adapting this should be a huge priority

[This has already happened](https://nutjs.dev/plugins/nl-matcher), but the plugin is only available to project sponsors.

Please read [this](https://nutjs.dev/blog/money) and [this](https://nutjs.dev/blog/apple-silicon-screencapture) blog post to understand why this is the case.

Sponsoring info can be found [here](https://nutjs.dev/#sponsoring)

All the best

Simon
