### ISSUE TITLE
Unable to use @nut-tree/template-matcher

### ISSUE THREAD

**Issue by kvcsks** [nut-tree/nut.js#496]
Unable to use @nut-tree/template-matcher.

**Desired execution environment / tested on**

_Visual Studio Code 
Version: 1.76.2 (system setup)
Commit: ee2b180d582a7f601fa6ecfdad8d9fd269ab1884
Date: 2023-03-14T17:55:54.936Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Windows_NT x64 10.0.19044
Sandboxed: No_

node -v: v19.1.0

`npm i @nut-tree/template-matcher` command throws following error:
```
npm ERR! Installing prebuilt OpenCV vundefined for plattform win32
npm ERR! prebuild-install WARN install No prebuilt binaries found (target=19.1.0 runtime=node arch=x64 libc= platform=win32)   
npm ERR! npm ERR! code ETARGET
```

**Comment by s1hofmann** [comment]
template matcher currently only supports up to node v16 or Electron v13. See https://github.com/nut-tree/TemplateMatcher
