### ISSUE TITLE
 Support mouse event monitoring

### ISSUE THREAD

**Issue by boxizen** [nut-tree/nut.js#497]
nut.js is awesome! Solve the problems that are difficult to overcome in daily work.

But I am curious whether it can support the monitoring of mouse events at present, or there are related plans?

Anyway, thank you for your contribution!

**Comment by s1hofmann** [comment]
Hi @boxizen 👋 

> nut.js is awesome! Solve the problems that are difficult to overcome in daily work.

Thank you very much!

> But I am curious whether it can support the monitoring of mouse events at present, or there are related plans?

Currently there’s no plan. Could you describe your use case and desired functionality?

All the best 

Simon

**Comment by mushan0x0** [comment]
I hope to support mouse event listening. Currently, I am using https://www.npmjs.com/package/uiohook-napi, but it crashes from time to time on macOS. I hope nut.js can replace it.  @s1hofmann

**Comment by huaerss** [comment]
I also have this problem and hope that nut can achieve this function.

**Comment by s1hofmann** [comment]
Mouse and keyboard event monitoring will soon land in nut.js

**Comment by s1hofmann** [comment]
Available in v4.5.0 with `@nut-tree/bolt@2.2.0`

https://nutjs.dev/blog/release450
