### ISSUE TITLE
`mouse.move(new Point(x, y))` not working in Windows 11

### ISSUE THREAD

**Issue by maifeeulasad** [nut-tree/nut.js#498]
**I'm trying to move my mouse curor into some top left position, then click on it. And finally try typing something. But it doesn't seem to be moving, although it's clicking and typing for sure**

**Desired execution environment / tested on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Code & More Details**
```
const {
  mouse,
  keyboard,
  sleep,
  Button,
  Point
} = require("@nut-tree/nut-js");
...
async function x(message){
  console.log(await mouse.getPosition())
  await mouse.move(new Point(200, 200));  // <---------- issue here
  await sleep(2000);
  await mouse.click(Button.LEFT);
  await sleep(2000);
  await keyboard.type(message);
}
...
(async () => {
  await x("meaw")
})();
```
It kept clicking a button, that's how I noticed it was clicking. Then I moved it on top of notepad, and started a program, it was typing, but real slow.

*Now the question remains, why can't I move my mouse?*

**Comment by s1hofmann** [comment]
Hi @maifeeulasad 👋 

`mouse.move` expects an array of points to follow along.

- [API](https://nut-tree.github.io/apidoc/classes/mouse_class.MouseClass.html#move) 
- [Getting started tutorial ](https://nutjs.dev/tutorials/first_steps) 

Explicitly setting the cursor position is done via [setPisition](https://nut-tree.github.io/apidoc/classes/mouse_class.MouseClass.html#setPosition) 

I’m considering the edge case of a single point for `move`, but I’d create a separate ticket for that.

All the best 

Simon
