### ISSUE TITLE
Error: [nut.js] - Error: Invalid key flag specified.

### ISSUE THREAD

**Issue by pablohpsilva-forjnetwork** [nut-tree/nut.js#506]
**Version**
"@nut-tree/nut-js": "^3.1.1",

**Short overview**
Whenever I have multiple keys being pressed like:
```
keyboard.pressKey(Key.RightCmd, Key.RightBracket);
// or 
keyboard.type(Key.RightCmd, Key.RightBracket);
```

Thea application throws an exception: 
(node:32260) UnhandledPromiseRejectionWarning: Error: [nut.js] - Error: Invalid key flag specified.

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

I'm using a Macbook Pro M1, latest MacOS.
Running nut-js in the latest electron.

**Steps to reproduce error**

Simply call the following like without a try-catch (so it will force an exception):
```
keyboard.pressKey(Key.RightCmd, Key.RightBracket);
```

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by s1hofmann** [comment]
Hi @pablohpsilva-forjnetwork :wave:

This is a known issue and is planned for v3.1.2: https://github.com/nut-tree/nut.js/issues/490
