### ISSUE TITLE
Win 11, WSL2 (ubuntu22.04lts), npm 9.5.1, node.js 18.16.0, is not ale to install @nut-tree/template-matcher successfully

### ISSUE THREAD

**Issue by michelleXIE2014** [nut-tree/nut.js#509]
**Is not ale to install @nut-tree/template-matcher successfully**

**Desired execution environment / tested on**

- [ ] Virtual machine
- [ ] Docker container
- [V] Dev/Host system: Win 11, wSL2, npm 9.5.1, node.js 18.16.0

**Detailed question**
When I ran npm
the error is like this
"npm ERR! code 1
npm ERR! path \\wsl.localhost\Ubuntu-22.04\home\mxie\repo\ecidcaJSTests\node_modules\opencv4nodejs-prebuilt
npm ERR! command failed
npm ERR! command C:\WINDOWS\system32\cmd.exe /d /s /c prebuild-install || (node ./install/dependencies.js && node ./install/install.js)
npm ERR! '\\wsl.localhost\Ubuntu-22.04\home\mxie\repo\ecidcaJSTests\node_modules\opencv4nodejs-prebuilt'
npm ERR! CMD.EXE was started with the above path as the current directory.
npm ERR! UNC paths are not supported.  Defaulting to Windows directory.
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Windows\package.json'
npm ERR! Require stack:
npm ERR! - \\wsl.localhost\Ubuntu-22.04\home\mxie\repo\ecidcaJSTests\node_modules\napi-build-utils\index.js
npm ERR! - \\wsl.localhost\Ubuntu-22.04\home\mxie\repo\ecidcaJSTests\node_modules\prebuild-install\bin.js
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19)
npm ERR!     at require (node:internal/modules/cjs/helpers:110:18)
npm ERR!     at Object.<anonymous> (\\wsl.localhost\Ubuntu-22.04\home\mxie\repo\ecidcaJSTests\node_modules\napi-build-utils\index.js:5:11)
npm ERR!     at Module._compile (node:internal/modules/cjs/loader:1254:14)
npm ERR!     at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
npm ERR!     at Module.load (node:internal/modules/cjs/loader:1117:32)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:958:12)
npm ERR!     at Module.require (node:internal/modules/cjs/loader:1141:19) {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: [
npm ERR!     '\\\\wsl.localhost\\Ubuntu-22.04\\home\\mxie\\repo\\ecidcaJSTests\\node_modules\\napi-build-utils\\index.js',
npm ERR!     '\\\\wsl.localhost\\Ubuntu-22.04\\home\\mxie\\repo\\ecidcaJSTests\\node_modules\\prebuild-install\\bin.js'
npm ERR!   ]
npm ERR! }
npm ERR!
npm ERR! Node.js v18.16.0
npm ERR! node:internal/modules/cjs/loader:1078
npm ERR!   throw err;
npm ERR!   ^
npm ERR!
npm ERR! Error: Cannot find module 'C:\Windows\install\dependencies.js'
npm ERR!     at Module._resolveFilename (node:internal/modules/cjs/loader:1075:15)
npm ERR!     at Module._load (node:internal/modules/cjs/loader:920:27)
npm ERR!     at Function.executeUserEntryPoint [as runMain] (node:internal/modules/run_main:81:12)
npm ERR!     at node:internal/main/run_main_module:23:47 {
npm ERR!   code: 'MODULE_NOT_FOUND',
npm ERR!   requireStack: []
npm ERR! }
npm ERR!
npm ERR! Node.js v18.16.0

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\mxie\AppData\Local\npm-cache\_logs\2023-05-02T21_20_36_400Z-debug-0.log"

**Comment by s1hofmann** [comment]
Hi @michelleXIE2014 👋 

`@nut-tree/template/matcher` is not yet compatible with node 18 or later. See 

https://github.com/nut-tree/TemplateMatcher/blob/develop/README.md

and

https://github.com/nut-tree/nut.js/issues/478

It is also not possible to run a Windows automation from within WSL, please use e.g. PowerShell
