### ISSUE TITLE
run screen.colorAt() crash when position  is negative value. [Two monitors]

### ISSUE THREAD

**Issue by rtugeek** [nut-tree/nut.js#511]
**Version**
^3.1.1

**Steps to reproduce error**
I have two monitors, and when I move the mouse to the left monitor, the X coordinate of the mouse becomes negative, causing the program to crash.
```
const {mouse, screen} = require("@nut-tree/nut-js");

setInterval(async () => {
    screen.colorAt(mouse.getPosition()).then((color) => {
        console.log(color.toHex());
    });
},1000)
```

**Comment by s1hofmann** [comment]
This is currently intended behaviour as we are only supporting single screen setups for now.
