### ISSUE TITLE
[Windows] [Clipboard] it opens a "Clipboard" app before pasting

### ISSUE THREAD

**Issue by cezarsmpio** [nut-tree/nut.js#515]
**Short summary**

I'm trying to use the Clipboard API and whenever I try to paste the content, a Clipboard window is open so the user must manually click to paste the desired text.

That's my code:

```ts
export const sendData = async (_, { settings }) => {
  keyboard.config = {
    autoDelayMs: 10,
  };

  const originalClipboard = await clipboard.getContent();

  await clipboard.setContent(settings.global.input);

  await keyboard.pressKey(Key.LeftSuper, Key.V);
  await keyboard.releaseKey(Key.LeftSuper, Key.V);

  await clipboard.setContent(originalClipboard);

  return true;
};
```

This is what happens on Windows:

![image](https://github.com/nut-tree/nut.js/assets/954889/f7e780b8-a8e8-43c4-a0cc-a091266fb1e3)

**Desired execution environment / tested on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed question**

Is there a way to prevent this from happening?

Also, it randomly throws some errors, such as:

```
node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe --paste\nthread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: \"The operation completed successfully.\" } }', src\\libcore\\result.rs:906:4\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.
```

**Comment by s1hofmann** [comment]
Hey @cezarsmpio 👋 

this is actually what I'd expect, given your script.

```js
await keyboard.pressKey(Key.LeftSuper, Key.V);
await keyboard.releaseKey(Key.LeftSuper, Key.V);
```

presses the `Win+V` shortcut.
Assuming you have [clipboard history](https://support.microsoft.com/en-us/windows/get-help-with-clipboard-30375039-ce71-9fe4-5b30-21b7aab6b13f) turned on, this leads to showing the clipboard history window.

**Comment by cezarsmpio** [comment]
Hey @s1hofmann , sorry, got a busy week those days and I couldn't reply you.

Your comment makes sense, before using `LeftSuper`, I was checking if the OS was windows, then using `Key.CtrlLeft` instead, but when doing this, I was getting this error:

```
node_modules\\clipboardy\\fallbacks\\windows\\clipboard_x86_64.exe --paste\nthread 'main' panicked at 'Error: Could not paste from clipboard: Error { repr: Os { code: 0, message: \"The operation completed successfully.\" } }', src\\libcore\\result.rs:906:4\nnote: Run with `RUST_BACKTRACE=1` for a backtrace.
```

Using `Key.SuperLeft` throws this error sometimes.
