### ISSUE TITLE
How to get the software that is running on the system.

### ISSUE THREAD

**Issue by Jarvie789** [nut-tree/nut.js#516]
**Short summary**

nut.js is really nice, but I have a question about how to get the software that is running on the system, for example, I minimized the Chrome window and then I want Chrome to be the active window (focus)

**Desired execution environment / tested on**

Macos,Linux,Windows

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Comment by s1hofmann** [comment]
Hi @Jarvie789 👋 

there’s already #172 to track this, it’s currently a work in progress and not yet possible.
I’ll close this issue in favor of the older one.

> nut.js is really nice

Thank you!

Best regards 

Simon
