### ISSUE TITLE
pressKey and releaseKey not actually holding key

### ISSUE THREAD

**Issue by JijaProGamer** [nut-tree/nut.js#524]
**Version**

0.6.13

**Short overview**

pressKey and releaseKey arent doing what they are made to do, releaseKey does nothing and pressKey just holds for 1 ms

**Issue occurs on**

Windows 11 Pro 22H2

**Steps to reproduce error**

```
import {keyboard, Key} from "@nut-tree/nut-js";

keyboard.config.autoDelayMs = 10;

keyboard.pressKey(Key.A);

setTimeout(() => {
          keyboard.releaseKey(Key.A);
}, 1000);
```

In your example you said its supposed to hold A, but it just presses A for 1 ms

**Comment by s1hofmann** [comment]
Hi @JijaProGamer 👋 

> Version 0.6.13

I'm a bit confused, which version of nut.js are you using?

> pressKey and releaseKey arent doing what they are made to do

The example is worded badly.
What "presses and holds keys" actually refers to, are modifiers.
When e.g. pressing the left shift key, followed by multiple key presses on e.g. `a`, `s`, `d`, `f`, the shift modifier would still be "held" and applied to the input. Same goes for mouse clicks.

If you want to repeatedly press a key, wrap it in `setInterval(...)`

Best regards

Simon
