### ISSUE TITLE
Exclamation mark is a one?

### ISSUE THREAD

**Issue by HazelNutHoney** [nut-tree/nut.js#531]
When I use NutTree/nut.js to send a message if it includes a exclamation mark ("!") then it will replace only the exclamation mark with the number one 

Let's say the message is "Hello, World!"
```
ipcMain.handle('sendMessage', (e, message) => {
  keyboard.config.autoDelayMs = 0;
  keyboard.type(message);
});
```
Expected output in my electron app "Hello, World!"

But what actually is returned "Hello, World1"

and I have tested it with other things like just the exclamation make for some reason it is always replaced with a one

Affected version that I tested was 3.1.2

**Comment by s1hofmann** [comment]
Hi @HazelNutHoney 👋 

Which OS are you testing on? I'm assuming it's Linux?

**Comment by HazelNutHoney** [comment]
@s1hofmann yes I am testing it on linux

**Comment by HazelNutHoney** [comment]
I was in the key.enum.d.ts file and it doesn't even have a colon, exclamation mark, question mark, or even a ampersand in it

**Comment by HazelNutHoney** [comment]
@s1hofmann I think I have found out how to fix it if I make nut-js pres shift before typing the character it will do the counter part so it's typing one cuz nut-js isn't pressing shift same with the ampersand and the other keys those are the secondary keys you have to hold shift for so when I use the pressKey function I am using keyboard.pressKey(Key.LeftShift, Key.Num1) keyboard.releaseKey(Key.LeftShift) then it will do a exclamation mark.

**Comment by HazelNutHoney** [comment]
Ah that makes sense

**Comment by s1hofmann** [comment]
I'll close this issue then.
