### ISSUE TITLE
Obtaining color at data

### ISSUE THREAD

**Issue by Ooshkar** [nut-tree/nut.js#537]
So i am trying to find the pixel color at a certain point, i have no debug errors or anything i have tried setting it as a variable and console logging it but still did not work

Code:
```js
const cv = require('opencv-bindings');
const keyboardjs = require('keyboardjs');
const {mouse, straightTo, Point, click, screen, RGBA} = require('@nut-tree/nut-js');

pos1=101
pos2=126
pos3=151

screen.colorAt(new Point(1000, 1000))

console.log(RGBA)
```

**Comment by Ooshkar** [comment]
also im trying to print the rgba out put

**Comment by s1hofmann** [comment]
Hi @Ooshkar 👋 

a simple example to get you started would look like this:

```js
const {Point, screen} = require('@nut-tree/nut-js');

(async () => {
  const colorAtPoint = await screen.colorAt(new Point(1000, 1000));
  console.log(colorAtPoint);
})();
```

But since this isn't exactly an issue, I'll close it.

Best regards

Simon
