### ISSUE TITLE
If pressing 

### ISSUE THREAD

**Issue by Ooshkar** [nut-tree/nut.js#538]
is there a way to make it where you do if key.k === pressed then does what ever it does i dont know if im stupid, i cant figure out how to do this becuase i cant keep the code alive for long enouph and just turns of the code in one second that there isnt a operation to do

**Comment by Ooshkar** [comment]
Also im trying to make a macro type thing for a game and im having a hard time making the mouse move the player (aka mc)
(async () => {
    await mouse.move(straightTo(new Point(10, 10)));
})();
so at this point it has alr interacted with the game by clicking on it and should be able to controll it but it doesnt, is this cus of some dark magic?

**Comment by Ooshkar** [comment]
> Also im trying to make a macro type thing for a game and im having a hard time making the mouse move the player (aka mc) (async () => { await mouse.move(straightTo(new Point(10, 10))); })(); so at this point it has alr interacted with the game by clicking on it and should be able to controll it but it doesnt, is this cus of some dark magic?

nvm works

**Comment by Ooshkar** [comment]
> is there a way to make it where you do if key.k === pressed then does what ever it does i dont know if im stupid, i cant figure out how to do this becuase i cant keep the code alive for long enouph and just turns of the code in one second that there isnt a operation to do

but still this

**Comment by morisok31** [comment]
well at least it works now

**Comment by Ooshkar** [comment]
> well at least it works now

nope

**Comment by s1hofmann** [comment]
Hi @Ooshkar 👋 

this is currently not supported, see #479

**Comment by Ooshkar** [comment]
thank you
