### ISSUE TITLE
keyboard.type(text) result in to multiple characters typing

### ISSUE THREAD

**Issue by pycraft114** [nut-tree/nut.js#539]
**Version**

3.1.2

**Short overview**

keyboard.type("hi i am danny from alex nice to meet you") result in to typing "i  ii. aamm. ddaannnnyy. ffrroomm  aalleexx. nniiccee. ttoo. mmeeeett. yyoouu"

**Issue occurs on**

- [ ] Virtual machine
- [ ] Docker container
- [x] Dev/Host system

**Detailed error description**

**Steps to reproduce error**

**Additional content**

> Please provide any (mandatory) additional data to reproduce the error (Dockerfiles etc.)

**Comment by pycraft114** [comment]
@s1hofmann 
https://github.com/nut-tree/nut.js/issues/460
i tried the copy pasting way too but it paste double times

**Comment by pycraft114** [comment]
closing this issue cause i found out that it was electron side issue

**Comment by s1hofmann** [comment]
Hi @pycraft114 👋 

could you maybe link related info that lead to closing this issue?

**Comment by pycraft114** [comment]
@s1hofmann I found out that it only happened in electron dev mode. since it runs initial useEffect twice in the strict mode which led to calling the function twice it pasted text twice @s1hofmann

**Comment by s1hofmann** [comment]
Thanks for the info, @pycraft114 👍

**Comment by pycraft114** [comment]
Kudos to nut js!! Such a nice library @s1hofmann
