### ISSUE TITLE
Keyboard keys not working in some input languages / layouts

### ISSUE THREAD

**Issue by sami-azzam** [nut-tree/nut.js#542]
**Version** 3.1.2

**Short overview** 
I'm trying to copy selected text using `await keyboard.type(Key.LeftControl, Key.C)` 
This works fine if the keyboard input language is set to English (US 101).
However, when I switch to other keyboard input languages such as Arabic, it does not work.

I also tried 
```js
await keyboard.pressKey(Key.LeftControl, Key.C);
await keyboard.releaseKey(Key.LeftControl, Key.C);
```

But with no luck as well.

Is there anything I can do to force it to use the US layout when sending keys?

**Issue occurs on** 
- [x] Virtual machine
- [x] Dev/Host system
- [ ] Docker container

**node version**: v20.3.1

**OS type and version**: Windows 11 

**Full code sample to reproduce**
```js
await keyboard.type(Key.LeftControl, Key.C)
``` 

**Notes**
I'm using Electron 25.2.0

**Comment by s1hofmann** [comment]
Hi @sami-azzam 👋 

currently not, but I’m planning to re-do the keyboard implementation to make solve this source of confusion and errors.

Best regards 

Simon

**Comment by sami-azzam** [comment]
Hey @s1hofmann 👋🏻

Thanks a lot for the quick reply!

I like using nut.js instead of robot.js. But, in the meantime, do you have any idea if robot.js will cause the same issue? or would it work if I use it temporarily for this task?

**Comment by sami-azzam** [comment]
UPDATE:
I found out that Ctrl+Insert also copies on Windows, and I was able to use `keyboard.type(Key.LeftControl, Key.Insert)`. 
I assume this is since the `Insert` key is not dependent on language and/or keyboard layout. 

@s1hofmann, please let me know if I'm missing anything here. I only tried on Arabic so far. Could this cause other issues in any of the other keyboard layouts?

Thanks for your support 👍🏻

**Comment by s1hofmann** [comment]
Hi @sami-azzam 👋 

this should be fine.
You can take a look at this really helpful collection of different keyboard layouts on Windows: https://learn.microsoft.com/en-us/windows-hardware/manufacture/desktop/windows-language-pack-default-values?view=windows-11
