### ISSUE TITLE
No such file or directory for clipboardy/package.json in some devices on Electron build

### ISSUE THREAD

**Issue by sami-azzam** [nut-tree/nut.js#543]
**Version**
3.1.2

**Short overview**
In my electron app, I got a report from a user (Windows 11) that they received this error:
![nut-js error](https://github.com/nut-tree/nut.js/assets/26723707/bdfe651b-4811-43f2-9d88-330aea03ea19)
Error content:

```
Uncaught Exception:
Error: ENOENT: no such file or directory, 
open '\\?\C:\Users\...\AppData\Local\Programs\...\resources\app.asar.unpacked\node_modules\clipboardy\package.json'
at Object.openSync (node:fs:601:3)
at Object.func [as openSync] (node:electron/js2c/asar_bundle:2:1822)
at Object.read FileSync (node:fs:469:35)
at treadFileSync (node:electron/js2c/asar_bundle:2:9165)
at h.internalModuleReadJSON (node:electron/js2c/asar_bundle:2:11704) 
at Object.read (node:internal/modules/package_json_reader:21:60)
at readPackage (node:internal/modules/cjs/loader:375:36) 
at resolveExports (node:internal/modules/cjs/loader:569:15) 
at Module._findPath (node:internal/modules/cjs/loader:641:31)
at Module._resolveFilename (node:internal/modules/cjs/loader:1068:27)
```

I was unable to replicate the issue in my Windows device.
I only used nut-js in one file in the main process.

**Issue occurs on**
- [x] Dev/Host system

**node version**:  18.15.0

**electron version**: 25.2.0

**OS type and version**: Windows 11

**Full code sample to reproduce** 
I was unable to reproduce, but here is the code I used:

```typescript
import { keyboard, Key } from "@nut-tree/nut-js";
// ...
if (process.platform === "win32") {
        // ...
        keyboard
          .type(Key.LeftControl, Key.Insert)
          .then(
           ()=>{
           // ...
          }
          )
          .then(() => {
               //...
          }
}
```

I am not using the clipboard interface from nut-js.

Please let me know if this issue is caused by nut-js or electron / build configuration, and if you have any information that could help.
I'm asking here because the only package I found that uses clipboardy in my app is nut-js and I couldn't replicate to investigate further.

Thanks a lot for your help.

**Comment by s1hofmann** [comment]
Hi @sami-azzam 👋 

that’s likely caused by the Electron bundling process.
Feel free to reopen if you think it’s something else.

Best regards 

Simon
