### ISSUE TITLE
Electron can't use @nut-tree/nut-js

### ISSUE THREAD

**Issue by Timson020** [nut-tree/nut.js#550]
**Version**
window: 10
@nut-tree/nut-js: 3.1.2
electron: 24.7.1
electron-builder: 24.9.1

***Error Msg**
Please configure thedynamicRequireTargets or/and ignoreDynamicRequires option of@rollup/plugin-commonjs appropriately for this require call to work

**Issue occurs on**

App is crash in start

- [ ] Virtual machine
- [ ] Docker container
- [ ] Dev/Host system

**node version**:
18.12.1

**Comment by s1hofmann** [comment]
Have you tried to configure `dynamicRequireTargets` as suggested in the error message?

`Please configure the dynamicRequire Targets or/and ignoreDynamicRequires option of @rollup/plugin-commonjs appropriately for this require call to work.`

**Comment by Timson020** [comment]
i try 
```js
plugin: [
  ...
  commonjs({ dynamicRequireTargets: './build/*.node' }),
]
```

but not work,

it message still here

**Comment by Timson020** [comment]
I try to use ```require``` replace ```import```
It is work

I think it error is caused by Vite

because i use webpack is ok ~
