### ISSUE TITLE
API docs

### ISSUE THREAD

**Issue by sancarn** [nut-tree/nut.js#87]
Documentation would be helpful

**Comment by s1hofmann** [comment]
Hi @sancarn, thanks for reaching out!

I'll start by adding API docs with proper explanation and samples.

**Comment by s1hofmann** [comment]
Docs generated via typedoc can be found [here](https://nut-tree.github.io/nut.js/).
Will be updated gradually

**Comment by sancarn** [comment]
Hi @s1hofmann 
Great work! Much better than last time I looked at this project and thanks for closing the issue as I wouldn't have seen it otherwise :)

Would be nice to add some simple samples of:
* Copy and Paste text
* Retrieve the region of a process window
* the screen module as a whole (find on screen, waitFor, and listeners)

**Comment by s1hofmann** [comment]
Hi @sancarn,

thanks for the kind words!
There will be an update in https://github.com/nut-tree/trailmix soon which covers usage with Electron.
I’ll consider moving the samples to a more prominent position!

Thanks for reaching out!

Best regards 

Simon
